Optimized the 'tobitmask' for Arm64.
facebookincubator/velox pull request #10856
Opened 2024-08-27 08:49 UTC by guyuqi

1. Added Arm64 implementation of `tobitmask`.
It's Arm64 equivalent implementation for x86 `movemasks`.
The implementation idea is from:
https://community.arm.com/arm-community-blogs/b/infrastructure-solutions-blog/posts/porting-x86-vector-bitmask-optimizations-to-arm-neon

3. The all cases in `velox_exec_test` were passed.
4. `velox_filter_benchmark`: 

Original:
```
[root@c542207d9649 tests]# ./velox_filter_benchmark
WARNING: Benchmark running in DEBUG mode
============================================================================
[...]/velox/type/tests/FilterBenchmark.cpp     relative  time/iter   iters/s
============================================================================
scalarDense                                                 5.58ms    179.33
simdDense                                       51.841%    10.76ms     92.97
scalarSparse                                                1.94ms    514.79
simdSparse                                      80.786%     2.40ms    415.88
```

Optimized:
```
[root@c542207d9649 tests]# ./velox_filter_benchmark
WARNING: Benchmark running in DEBUG mode
============================================================================
[...]/velox/type/tests/FilterBenchmark.cpp     relative  time/iter   iters/s
============================================================================
scalarDense                                                 5.59ms    178.95
simdDense                                       55.537%    10.06ms     99.38
scalarSparse                                                1.94ms    515.24
simdSparse                                      98.249%     1.98ms    506.22

```

5.  This PR firstly provided the Arm64 `tobitmask` API.  And the next step (will be in the other separated PR): 
Adjust `arm64bitmask` caller API in `Hashtable.cpp` to accelerate `HashJoin` performace on Arm64.

2024-08-27 15:12 UTC, Yuhta requested changes
The benchmark result does not look very promising.  Can you add the hash table change here and show the performance gain on hash table?  This may not worth the extra complicity if the gain is similar to what we see in `velox_filter_benchmark`.

2024-08-27 15:12 UTC, Yuhta commented on velox/common/base/BitUtil.h
> +  bits &= bits - 1;
I don't think it is correct to do this 4 times.  Also rename it to `getAndClearLast4SetBit` and remove `#if __ARM_ARCH` check

2024-08-27 15:12 UTC, Yuhta commented on velox/common/base/SimdUtil.h
> +auto arm64ToBitMask(xsimd::batch_bool<T, A> mask, const A& arch = {}) {
`to4BitsMask`

2024-08-27 15:12 UTC, Yuhta commented on velox/common/base/SimdUtil.h
> +#if __ARM_ARCH
`XSIMD_WITH_NEON`

2024-08-27 15:12 UTC, Yuhta commented on velox/type/tests/FilterBenchmark.cpp
> +#if __ARM_ARCH
`XSIMD_WITH_NEON`

2024-08-27 15:15 UTC, Yuhta commented on velox/common/base/BitUtil.h
> +  int32_t trailingZeros = __builtin_ctzll(bits) >> 2;
It is cleaner to just return the number of trailing zeros as it is and divided by 4 outside the call

2024-08-28 03:38 UTC, guyuqi commented
> The benchmark result does not look very promising. Can you add the hash table change here and show the performance gain on hash table? This may not worth the extra complicity if the gain is similar to what we see in `velox_filter_benchmark`.

Hi @Yuhta  Thanks for your comments. :-)
This New equivalent implementation leverages Arm neon `shrn`:
![image](https://github.com/user-attachments/assets/20af4532-0f9a-48b7-964c-8696af392f0b)
![image](https://github.com/user-attachments/assets/0193ed39-499f-46d2-82b6-5476c079f134)


It is apparently more efficient than the scalar implementation and naive Neon implementation:
Scalar:
```
template <typename T, typename A>
int genericToBitMask(xsimd::batch_bool<T, A> mask) {
  static_assert(mask.size <= 32);
  alignas(A::alignment()) bool tmp[mask.size];
  mask.store_aligned(tmp);
  int ans = 0;
  for (int i = 0; i < mask.size; ++i) {
    ans |= tmp[i] << i;
  }
  return ans;
}
```

naive Neon implementation:
```
  static int toBitMask(xsimd::batch_bool<T, A> mask, const xsimd::neon&) {
    alignas(A::alignment()) static const int8_t kShift[] = {
        -7, -6, -5, -4, -3, -2, -1, 0, -7, -6, -5, -4, -3, -2, -1, 0};
    int8x16_t vshift = vld1q_s8(kShift);
    uint8x16_t vmask = vshlq_u8(vandq_u8(mask, vdupq_n_u8(0x80)), vshift);
    return (vaddv_u8(vget_high_u8(vmask)) << 8) | vaddv_u8(vget_low_u8(vmask));
  }

```


It appears we could achieve a 20% performance improvement in `simdSparse` of `velox_filter_benchmark`.
 I'd like to refine the code based on your comments. 
Additionally, I'll need some time to add hash table change and will update you as soon as possible. Thanks.

2024-08-30 21:26 UTC, Yuhta commented
20% in `Filter::testValues` usually translates to no visible improvement for a query.  The improvement doesn't justify to keep 2 different formats for bitmask.  Can you canonicalize your 4 bits masks to the common ones and see if there is still improvement?

2024-12-18 07:51 UTC, closed without merging