Limit Dictionary to Single Level
facebookincubator/velox pull request #10942
Opened 2024-09-06 18:30 UTC by oerling

- Modifies wrapInDictionary to flatten indices of a wrapped dictionary iwth the wrapping indices.
- Makes lazy loading of a dictionary encoded column to combine the indices with a dictionary wrapper if loading with lazy wrapped in a dictionary.
- Adds functions to transpose dictionaries with and without nulls.
- Changes  NestedLoopJoin and MergeJoin so  that they wrap their input only after the wrapping indices are known. Previously these would wrap first and only then fill in the indices.
- Checks that we do not come across multiple nested dictionaries.

2024-11-08 15:46 UTC, assignUser requested changes

2024-11-08 15:46 UTC, assignUser commented on CMakeLists.txt
> +  # set_source(gRPC) resolve_dependency(gRPC)
:eyes:

2024-11-08 17:09 UTC, pedroerp requested changes
Please address comments and make sure CI is all green.

2024-12-18 20:45 UTC, xiaoxmeng reviewed
@oerling thanks for the update % minors. Thanks!

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/DecodedVector.cpp
> +          // LOG(ERROR) << "Multilevel dict ";
Remove this log

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +  int32_t i = 0;
```
static_assert(kBatch == 8);
static_assert(sizeof(vector_size_t) == sizeof(int32_t));
```

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +        xsimd::batch<int32_t>::broadcast(0), mask, base, indexBatch)
this won't overwrite beyond the size? Or the buffer is padding to xsimd batch aligned? thanks!

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +    const vector_size_t* base,
```
s/base/baseIndices/
s/size/wrapSize/
s/indices/wrapIndices/
s/result/resultIndices/
```

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.h
> +      vector_size_t* result,
```
s/result/resultIndices/
```

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.h
> +      vector_size_t size,
```
s/size/wrapSize/
```

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +    static_assert(sizeof(vector_size_t) == sizeof(int32_t));
We just need to check it once before the loop.

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +      uint8_t baseNullBits = simd::gather8Bits(baseNulls, indexBatch, 8);
What if i + kBatch> size?

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +  if (wrapIndices->refCount() > 1) {
Can we use unique method here?

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +    if (!wrapNulls || wrapNulls->refCount() > 1) {
ditto

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +      base->containsLazyAndIsWrapped_ = false;
Any check on this if possible? containsLazyAndIsWrapped_ can never be true?

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +    if (indices->refCount() > 1) {
ditto

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +    auto base = vector->valueVector();
```
s/base/baseValue/
```

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +    auto* rawNulls = vector->rawNulls();
```
s/rawNulls/rawBaseNulls/
```

2024-12-18 20:45 UTC, xiaoxmeng commented on velox/vector/BaseVector.cpp
> +      auto newNulls = AlignedBuffer::allocate<bool>(size, vector->pool());
We can't reuse here?

2025-04-03 01:22 UTC, closed without merging