Support sparksql approx_percentile
facebookincubator/velox pull request #11033
Opened 2024-09-18 23:33 UTC by WangGuangxin

Different with Presto's implementation in following folds:
1. It didn't check the intermediate type in `checkIntermediateInputs` when `addIntermediateResults` since after Spark's Shuffle, the encoding of input vectors are always flattened.
2. The third input argument ( aka. accuracy) in spark is a Integer, while it's a double in Presto.

2024-09-19 00:08 UTC, Yuhta requested changes
The duplication is too high, can we start by extracting reusable parts first?  If only check and signature is the difference, the most of the code can be reused.

2024-09-19 00:20 UTC, WangGuangxin commented
cc @PHILO-HE

2024-09-23 00:52 UTC, PHILO-HE commented
@WangGuangxin, could you address the comment from @Yuhta?

2024-09-25 15:07 UTC, WangGuangxin commented
> @WangGuangxin, could you address the comment from @Yuhta?

sure

2024-09-26 02:31 UTC, jinchengchenghh commented on velox/functions/sparksql/aggregates/ApproxPercentileAggregate.cpp
> +} // namespace facebook::velox::functions::aggregate::sparksql
Add the empty line in the end.

2024-09-26 02:31 UTC, jinchengchenghh commented on velox/functions/sparksql/aggregates/Register.cpp
> +    bool overwrite);
Add the empty line.

2024-09-26 02:32 UTC, jinchengchenghh commented
We may support dictionary encoding in Gluten native shuffle.

2024-09-26 02:33 UTC, jinchengchenghh commented
Can we move the implement to folder lib so we can reuse the most code of Presto.

2025-01-11 04:41 UTC, closed without merging