Suppress nullabillity completeness for clang
facebookincubator/velox pull request #11218
Opened 2024-10-10 08:31 UTC by JackyWoo

Fix #11217

### Changelog
1. Add warnings.cmake to configure global (not a target-specific one) warning settings.
2. Suppress nullabillity completeness in clang.

2024-10-11 03:13 UTC, assignUser requested changes
First of, I appreciate your eagerness to contribute to the velox build system, thanks!

We already disable that warning [here](https://github.com/facebookincubator/velox/blob/main/CMakeLists.txt#L345), I suspect the actual issue is that you are using `AppleClang` which our logic isn't setup for but could be fixed easily by extending the `if` condition. Please try that.

And while I know our current system for warnings isn't ideal I am already working on a comprehensive refactor, so please fix the current sytem for now.

2024-10-11 03:13 UTC, assignUser commented on CMakeLists.txt
> -# build
As this comment says, this is very much on purpose down here.

2024-10-11 03:13 UTC, assignUser commented on CMake/Warnings.cmake
Please don't copy code from other projects without proper attribution. -> https://github.com/ClickHouse/ClickHouse/blob/master/cmake/add_warning.cmake is ASL 2.0 licensed so usage is no problem but would require an entry in the NOTICE file and a license header.

2024-10-11 03:38 UTC, JackyWoo commented
> We already disable that warning [here](https://github.com/facebookincubator/velox/blob/main/CMakeLists.txt#L345), I suspect the actual issue is that you are using AppleClang which our logic isn't setup for but could be fixed easily by extending the if condition. Please try that.

Actually I use Regular Clang but not Apple Clang. The no-nullability-completeness not work is because the default value of ENABLE_ALL_WARNINGS is blank.

2024-10-11 03:38 UTC, JackyWoo commented on CMake/Warnings.cmake
ok

2024-10-11 04:59 UTC, assignUser commented
It's not blank when the make file is used but that's another area I want to refactor ^^

2024-10-11 05:31 UTC, JackyWoo commented
It is better to make cmake and make behaviors consistent here.

2024-10-11 06:32 UTC, JackyWoo commented
Now it is ready to review.

2024-10-14 21:05 UTC, assignUser commented on CMakeLists.txt
I see where you are coming from but I think we can align with the make file better without moving the flags around by adding an `option(ENABLE_ALL_WARNINGS "Enable -Wall and -Wextra compiler warnings" ON)` at the top of file with the other options. We default it to on (which is what the make file does now as well).  This way the same happens via make or direct call of `cmake`.

2024-10-15 06:32 UTC, JackyWoo commented on CMakeLists.txt
Make `ENABLE_ALL_WARNINGS ` as an option is sensible.

But I think we still need move the flag around. Because when`ENABLE_ALL_WARNINGS ` off, flags `-Wall and -Wextra` and `-Wno-nullability-completeness` will not be set and we will got the build warning.

2024-10-15 08:07 UTC, assignUser commented on CMakeLists.txt
But wall and wextra will only be set if the option is on?

2024-10-15 09:24 UTC, JackyWoo commented on CMakeLists.txt
I guess yes based on the option name `ENABLE_ALL_WARNINGS `.

2024-10-16 03:39 UTC, JackyWoo commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${KNOWN_WARNINGS}")
ok

2024-10-18 14:00 UTC, assignUser approved these changes
Thanks! I have updated the title and description to match the current situation :)

2024-10-28 16:56 UTC, closed without merging