Add input generator for json_parse in expression fuzzer
facebookincubator/velox pull request #11466
Opened 2024-11-07 01:57 UTC by kagamiori

Summary: DO NOT REVIEW NOW.

Differential Revision: D65576377

2024-11-07 22:45 UTC, assignUser commented
Please set WIP PRs into draft mode (does not notify codeowners) until you want a review to reduce notification volume for codeowners :)

2024-11-08 03:34 UTC, kagamiori commented
> Please set WIP PRs into draft mode (does not notify codeowners) until you want a review to reduce notification volume for codeowners :)

Hi @assignUser, I tried but unfortunately couldn't find the convert-to-draft button from my side. I guess it's because this PR was exported from our internal system.

By the way, the failed CI jobs report an error during Configure Build as follows:
> CMake Error at velox/experimental/fuzzer_input_generator/CMakeLists.txt:26 (target_compile_options):
  target_compile_options can not be used on an ALIAS target.

But the reported CMakeLists file doesn't use an ALIAS target with target_compile_options. Do you know how I could address this error?
```
velox_add_library(
  velox_fuzzer_constrained_input_generators ConstrainedGenerators.cpp
  ConstrainedVectorGenerator.cpp)

velox_link_libraries(
  velox_fuzzer_constrained_input_generators
  Folly::folly
  velox_expression
  velox_type
  velox_vector_fuzzer_util)

if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  target_compile_options(velox_fuzzer_constrained_input_generators
                         PRIVATE -Wno-deprecated-declarations)
endif()
```

2024-11-08 14:58 UTC, assignUser commented
>But the reported CMakeLists file doesn't use an ALIAS target with target_compile_options. Do you know how I could address this error?

The mono library creates alias targets for all targets, so you have to check with `if(VELOX_MONO_LIBRARY)` and use `velox` as the target. Or if it's only one TU with the warnings you can set the flag on that source file with https://cmake.org/cmake/help/latest/command/set_source_files_properties.html this would then not set the flag on all files in velox.

2024-11-18 01:01 UTC, assignUser commented on velox/vector/fuzzer/CMakeLists.txt
> +  velox_presto_types velox_fuzzer_constrained_input_generators)
ah you always pull it in ok. If this always expected to be present, is it still experimental?

2024-11-18 19:32 UTC, kagamiori commented on velox/vector/fuzzer/Utils.cpp
> +#pragma clang diagnostic ignored "-Wdeprecated-declarations"
Hi @assignUser, the actual deprecated error was the following if I remove this #pragma. (https://github.com/facebookincubator/velox/actions/runs/11899400817/job/33157967625?pr=11466)
```
/Users/runner/work/velox/velox/./velox/experimental/fuzzer_input_generator/ConstrainedGenerators.h:107:10: error: 'wstring_convert<std::codecvt_utf8<char16_t>, char16_t>' is deprecated [-Werror,-Wdeprecated-declarations]
    std::wstring_convert<std::codecvt_utf8<char16_t>, char16_t> converter;
         ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/locale:3598:28: note: 'wstring_convert<std::codecvt_utf8<char16_t>, char16_t>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 wstring_convert
                           ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__config:1037:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__config:1010:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((__deprecated__))
```

I haven't been able to find a good way to resolve this build error. Here are the things I have tried: https://github.com/facebookincubator/velox/pull/11466#issuecomment-2474449460.

What I found interesting is that `std::wstring_convert<std::codecvt_utf8<>>` has been used in VectorFuzzer for 3 years and there hasn't been any build error about it. So I was wondering what's the difference there. Do you have any suggestion about how to resolve the build error in this PR? Thanks!

2024-11-21 00:41 UTC, assignUser commented on velox/vector/fuzzer/Utils.cpp
> +#pragma clang diagnostic ignored "-Wdeprecated-declarations"
>`<codecvt>` is deprecated in C++17 and removed in C++26 (see [P2871R3](https://wg21.link/P2871R3)).
>
>The reason for removal is that this feature no longer implements the current [Unicode Standard](https://>www.unicode.org/versions/latest/), supporting only the obsolete UCS-2 encoding.

https://en.cppreference.com/w/cpp/locale/wstring_convert

Hm you are right, no replacement.  I guess you'd need to write one yourself? Or use a library maybe icu4c?
Anyway that's probably a follow up for now you can use the gcc pragma ([clang understands them too](https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas)) to wrap the header/function:
```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

// the header

#pragma GCC diagnostic pop
```

2025-01-10 22:38 UTC, assignUser requested changes
Why should the generator that, afaiu is only supposed to be used for fuzzing be part of libvelox and link to the actual fuzzer? As type is core we would ALWAYS need to build with fuzzers?

2025-01-10 22:38 UTC, assignUser commented on velox/functions/prestosql/types/JsonType.cpp
> +        fuzzer::getRandomInputGenerator(
This is the cause of the missing symbol. The link to velox_fuzzer... is removed by the monolithic wrapper function. We could link this explicitly but to be honest I don't think the type defintion is the right place for an input generator?

2025-01-13 19:44 UTC, kagamiori commented on velox/functions/prestosql/types/JsonType.cpp
> +        fuzzer::getRandomInputGenerator(
Hi @assignUser, every custom type needs a logic to generate valid data, so the custom types and input generators are naturally bounded. So we add a new API getInputGenerator() to CustomTypeFactories to remind every custom type author to define the data generation logic intentionally. I'll try to move ConstrainedInputGenerators.h/cpp to another place not under fuzzer directories. Thank you for helping pinpoint the problem!

2025-01-14 03:12 UTC, kagamiori commented on velox/functions/prestosql/types/JsonType.cpp
> +        fuzzer::getRandomInputGenerator(
I'm moving ConstrainedInputGenerators.h/cpp to velox/common/fuzzer: https://github.com/facebookincubator/velox/pull/12080.

2025-01-15 23:51 UTC, kevinwilfong commented on velox/type/Type.h
> +  const TypePtr& representedType_;
Could we just let the JSON Generator call velox::randType(...) with a FuzzerGenerator created from seed_?

2025-01-15 23:51 UTC, kevinwilfong commented on velox/vector/fuzzer/VectorFuzzer.cpp
> +    // TODO: incorporate fuzzer options into customGenerator.
This comment feels like it would be more appropriate where we create the InputGeneratorConfig in VectorFuzzer.cpp.

2025-01-15 23:57 UTC, kevinwilfong commented on velox/vector/fuzzer/VectorFuzzer.cpp
> +    // TODO: incorporate fuzzer options into customGenerator.
Alternatively, JSON really only supports a handful of types: string, integer, float, object (map), array, and boolean (any of which can be null), so JSON could just randomly construct one of those if you don't want to link against VectorFuzzer in the Presto Type code.

2025-01-15 23:58 UTC, kevinwilfong commented on velox/type/Type.h
> +  const TypePtr& representedType_;
Alternatively, JSON really only supports a handful of types: string, integer, float, object (map), array, and boolean (any of which can be null), so JSON could just randomly construct one of those if you don't want to link against VectorFuzzer in the Presto Type code.

2025-01-17 18:57 UTC, kevinwilfong approved these changes
Thanks! LGTM

2025-01-22 23:04 UTC, closed without merging