refactor(parquet): Use velox parquet reader in FileSerializeTest
facebookincubator/velox pull request #11886
Opened 2024-12-17 04:31 UTC by jkhaliqi

2025-05-08 21:17 UTC, jkhaliqi commented
@PingLiuPing Refactoring the code to use velox parquet reader and get rid of the arrow reader `#include "velox/dwio/parquet/writer/arrow/tests/FileReader.h"` dependency.

2026-02-24 22:51 UTC, czentgr commented on velox/dwio/parquet/reader/TimestampColumnReader.h
> +  const uint64_t days = static_cast<uint64_t>(value >> 64);
Let's use `auto` here. The type is clear from the cast.

2026-02-24 22:51 UTC, czentgr commented on velox/type/Timestamp.h
> +  static Timestamp fromDaysAndNanos(T days, T nanos) {
The usage uses sometimes `uint64_t` (TimestampColumnReader Line 43) and sometimes `int64_t`. This harmonizes the type as well (before they were different).
It is possible maybe to get an overflow?
So maybe in the TimestampColumnReader we make sure that we don't overflow with a check and then we can use a cast to the int64_t type instead of templating?

2026-02-24 22:51 UTC, czentgr commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
> +  auto filePath = exec::test::TempFilePath::create();
I see this code being repeated multiplle times. Not all of it but a big chunk. Make we can refactor this into a util function?

2026-02-25 20:20 UTC, jkhaliqi commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
> +  auto filePath = exec::test::TempFilePath::create();
Seems like the duplication cannot be refactored, and it causes the tests to fail with any attempt of taking memoryPool initialization outside the tests.

2026-05-18 02:57 UTC, mbasmanova requested changes
Thank you for the refactoring effort!

**This PR mixes several unrelated changes.** Please split into separate PRs:
1. `CompressionKind_LZ4_HADOOP` addition and the LZ4 mapping change
2. `hasIndexPage()` metadata accessor
3. `fromDaysAndNanos` signature change (`int32_t` → `int64_t`) and inlining
4. The FileSerializeTest refactoring (the main goal)

Each change should be reviewable and landable independently.

**Please address @czentgr's outstanding comments** from February (use `auto`, overflow check for `fromDaysAndNanos`, code duplication in tests).

**`fromDaysAndNanos` moved to header.** The implementation is non-trivial (negative nanos handling) — per coding style it should stay in the `.cpp` file.

2026-07-30 21:19 UTC, jkhaliqi commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
> +  auto filePath = exec::test::TempFilePath::create();
`filePath`, `rootPool`, and `leafPool` must all outlive the `reader`, so a helper returning only the reader dangles. Bundling them in a struct fixed it.

2026-08-10 16:07 UTC, mbasmanova reviewed
@jkhaliqi Are you still working on this one? It has been open a long time with long gaps between rounds, so I wanted to check before spending more review cycles on it. If you do not have bandwidth right now that is completely understandable — we can close it and someone can pick the work up later. Just let us know either way.

Two things:

The description says this removes the Arrow Parquet reader dependency, but there are no CMake changes, and `tests/FileReader.h` is still included by `ColumnWriterTest.cpp`, `ParquetWriterTest.cpp` and `ParquetWriterFieldIdTest.cpp`, so the dependency stays. Could you file an issue, or point at an existing one, describing the overall goal of removing it and the steps to get there? This change is one of several, and that context would make each incremental PR much easier to review.

`ParquetReader::thriftFileMetaData()` has no callers anywhere in the repo. It also exposes the raw `thrift::FileMetaData` as public API on a core class, and it is why `ParquetStatsContext.h` was added to `ParquetReader.h`, which drags the generated thrift header into a public header for every includer. Please drop the accessor and the include.

CC: @czentgr

2026-08-11 19:00 UTC, jkhaliqi commented
@mbasmanova 
Yes, still actively on this — sorry for the long gaps. Both points addressed:

  Issue for the overall goal: #11399 already tracks this ("Use Velox Parquet Reader in the Parquet Writer tests"), so I've linked this PR to it rather than filing a new one, and added a comment there with the full inventory: every file still
  including tests/FileReader.h, what each one uses the Arrow reader for, and the step order. The last two steps are the substantive ones. ParquetWriterTest.cpp's page-index test needs reader API that doesn't exist yet — ColumnChunkMetaDataPtr has hasColumnIndex()/hasOffsetIndex() but no way to read the index bodies. ColumnWriterTest.cpp asserts per-page numRows/numValues/numNulls on DataPageV2, which needs a different approach against Velox's PageReader. Those two gate the CMake deletion, which is why it lands last.

  thriftFileMetaData(): removed, along with the ParquetStatsContext.h include. It had no callers, as you mentioned.
  
  One note on that second point: dropping the include doesn't stop the generated thrift header from reaching includers of ParquetReader.h. It also includes reader/Metadata.h, which includes parquet/thrift/ParquetThrift.h directly at line 21,
  and did so before this PR. Removing the accessor and include is still right, but the thrift-in-a-public-header problem is pre-existing and lives in Metadata.h. It also isn't a one-line fix there: Metadata.h uses thrift types in its public
  signatures — thrift::ConvertedType and thrift::LogicalType parameters on getColumnStatistics(), and std::vector<thrift::Encoding> returned from encodings() — and those have callers outside the reader that pass and consume the thrift types directly. Removing the include means changing those signatures, so I'll file a separate issue for it rather than expanding this PR.

  I also rewrote the description to scope the removal claim to FileSerializeTest and say explicitly why there's no CMake change yet.

2026-08-12 01:57 UTC, PingLiuPing requested changes
Thanks.

2026-08-12 01:57 UTC, PingLiuPing commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
> +    propBuilder.disableDictionary();
This changes what the writer test covers: the old test used the default writer properties, where dictionary encoding is enabled by default for non-Boolean columns, but the Velox-reader version no longer exercises dictionary-enabled writes for these types.

2026-08-12 01:57 UTC, PingLiuPing commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
> +    rowReader->next(batchSize, result);
`ParquetRowReader::next()` reads at most the current row group, so with four row groups this validates values from the first row group and never reads/verifies the remaining three. The metadata loop below still walks all row groups, but the actual data roundtrip no longer matches the old `for (rg)` / `readBatch()` coverage. Please read until EOF and compare all `numRows_` rows, or explicitly read and validate each row group. See old line 184-186.

2026-08-12 01:57 UTC, PingLiuPing commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
> +  rowReader->next(batchSize, result);
Here ignores the return value from `rowReader->next()` and has no assertion on `result->size()`,  a reader that returns zero rows would make the loop skip and the test pass.

2026-08-12 14:07 UTC, mbasmanova requested changes
Thank you for picking this back up, and for the inventory on #11399.

**Please don't grow `TestUtil`.** It is already 956 lines of unrelated helpers
— data directories, vector comparison, slicing, random generators, encoders,
`MockPageReader`, `DataPageBuilder` — and the style guide bans this naming
precisely because such files accumulate anything useful to more than one test
(CODING_STYLE.md, "Never name a file or class `*Utils`, `*Helpers`, or
`*Common`"). Consolidating the three copies of `writeToFile` is right, but it
belongs in a `ParquetTestFile` class in its own header, with static `write()`
and `open()` — the class name supplies the context, so the methods stay short.
`createReaderContext` belongs there too: it is the other half of the same
concept, and `FileDeserializeTest.cpp:973,1033` and `MetadataTest.cpp:400,523`
still open-code the same buffer-to-file-to-`ParquetReader` sequence.

**Values are checked by parsing `toString()`.** `MultiPageDisabledDictionary`
recovers each integer with `substr` + `std::stoi` on `result->toString(j)`, and
`AllNulls` checks nullness by stripping braces and spaces, splitting on commas,
and comparing each token to `"null"`. Both depend on `RowVector::toString`'s
formatting, which is a debugging aid rather than a stable contract. Please
build the expected vector and use `assertEqualVectors`
(`velox/vector/tests/utils/VectorTestBase.h:43`), which covers values and nulls
together, or `BaseVector::variantAt` (`velox/vector/BaseVector.h:888`) where a
single element is all you need.

**The LZ4 comment describes a failure that does not happen.** "Compression type
LZ4 causes loadedVector() to fail with decompressed block size being way bigger
than 200..." sits directly above the `loadedVector()` loop, but `SmallFileLz4`
and `SmallFileLz4Hadoop` both run unguarded and CI is green. Either it is stale
and should be removed, or the reader bug is real — in which case it needs an
issue and the test needs to say what it does about it.

**`createRowBasedOnType` repeats the column list seven times.** Please rename it
to `createRowType` and drop the `if constexpr` ladder:
`ROW(std::vector<std::string> names, const TypePtr& childType)`
(`velox/type/Type.h:1909`) builds a row of one repeated type, and
`CppToType<typename TestType::CType>::create()` (`velox/type/CppToType.h`)
gives the element type for everything except Int96, ByteArray and FLBA.

**`50` is `rowsPerRowgroup_`.** The four `ASSERT_EQ(column->size(), 50)`
hardcode the value the line above already asserts through the member. Please
use it. `AllNulls` also declares `int pos = 0;` and never uses it.

2026-08-14 09:30 UTC, PingLiuPing requested changes

2026-08-14 09:30 UTC, PingLiuPing commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
fileSerializeTest codec mapping has no `thrift::CompressionCodec::BROTLI`. So any build with `ARROW_WITH_BROTLI` will now fail this test instead of preserving the old Arrow-reader coverage.

2026-08-14 18:13 UTC, jkhaliqi commented on velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp
Good catch. Adding a `BROTLI` case wouldn't fix it, though — `common::CompressionKind` has no Brotli entry, so `thriftCodecToCompressionKind` throws `VELOX_UNSUPPORTED`, and the roundtrip read fails before the mapping is even reached since the Velox reader has no Brotli decompressor. Making this test pass would mean adding Brotli support to `velox/common/compression`, which feels out of scope for this PR — we could file a follow-up issue if you think it's worth having.

This also looks latent rather than an active break: nothing defines `ARROW_WITH_BROTLI` for Velox's own sources (the `ARROW_WITH_*` flags in `scripts/setup-common.sh` are options for the bundled Arrow build, and Brotli isn't among them), so the block has never compiled. I removed `SmallFileBrotli` and changed the mapping's `default:` from silently asserting `CompressionKind_NONE` to `FAIL()` with the codec name, so a future unmapped codec fails loudly instead of asserting the wrong expectation. Writer-side Brotli coverage is unaffected — `ColumnWriterTest` still has three Brotli tests and reads pages back with the arrow `PageReader`, not the Velox reader.

2026-08-28 03:25 UTC, PingLiuPing approved these changes
Thanks.

2026-08-28 08:54 UTC, PingLiuPing commented
@jkhaliqi Would you please rebase and trigger the CI again, the building error seems not relate to your code.

2026-09-01 23:41 UTC, kagamiori commented
Hi @jkhaliqi, could you please rebase onto the latest main? Thanks!

2026-09-03 18:45 UTC, kagamiori commented
Failed to merge this PR due to previous change-request by @mbasmanova. @mbasmanova, could you take another look at this PR? Thanks!

2026-09-03 19:23 UTC, mbasmanova approved these changes

2026-09-03 20:46 UTC, merged