feat: Optimize deserialize UnsafeRows to RowVector
facebookincubator/velox pull request #11936
Opened 2024-12-23 08:45 UTC by jinchengchenghh

The old API extracts the single data to std::string_view, which is not efficient, This new approach aligns with CompactRow deserialization, the benchmark shows it accelerates 35% to 3x times depending on the actual row type.
Deprecated the old UnsafeRowDeserializer API if this is adopted.
```
velox/build/velox/row/benchmarks# ./velox_unsafe_row_serialize_benchmark
============================================================================
[...]marks/UnsafeRowSerializeBenchmark.cpp     relative  time/iter   iters/s
============================================================================
unsafe_deserialize_fixedWidth5                             52.83us    18.93K
unsafe_deserialize_fast_fixedWidth5             175.16%    30.16us    33.16K
unsafe_deserialize_fixedWidth10                           273.26us     3.66K
unsafe_deserialize_fast_fixedWidth10            311.01%    87.86us    11.38K
unsafe_deserialize_fixedWidth20                           206.03us     4.85K
unsafe_deserialize_fast_fixedWidth20            205.86%   100.08us     9.99K
unsafe_deserialize_strings1                                54.58us    18.32K
unsafe_deserialize_fast_strings1                156.14%    34.96us    28.61K
unsafe_deserialize_strings5                               204.10us     4.90K
unsafe_deserialize_fast_strings5                159.48%   127.98us     7.81K
unsafe_deserialize_arrays                                 158.01us     6.33K
unsafe_deserialize_fast_arrays                  222.55%    71.00us    14.08K
unsafe_deserialize_nestedArrays                           231.72us     4.32K
unsafe_deserialize_fast_nestedArrays            165.38%   140.11us     7.14K
unsafe_deserialize_maps                                   396.14us     2.52K
unsafe_deserialize_fast_maps                    320.59%   123.56us     8.09K
unsafe_deserialize_structs                                148.35us     6.74K
unsafe_deserialize_fast_structs                 135.53%   109.46us     9.14K
```

2025-01-16 02:07 UTC, jinchengchenghh commented
Before change to std::vector<char*>,
```
```
velox/build/velox/row/benchmarks# ./velox_unsafe_row_serialize_benchmark
============================================================================
[...]marks/UnsafeRowSerializeBenchmark.cpp     relative  time/iter   iters/s
============================================================================
unsafe_deserialize_fixedWidth5                             52.83us    18.93K
unsafe_deserialize_fast_fixedWidth5             175.16%    30.16us    33.16K
unsafe_deserialize_fixedWidth10                           273.26us     3.66K
unsafe_deserialize_fast_fixedWidth10            311.01%    87.86us    11.38K
unsafe_deserialize_fixedWidth20                           206.03us     4.85K
unsafe_deserialize_fast_fixedWidth20            205.86%   100.08us     9.99K
unsafe_deserialize_strings1                                54.58us    18.32K
unsafe_deserialize_fast_strings1                156.14%    34.96us    28.61K
unsafe_deserialize_strings5                               204.10us     4.90K
unsafe_deserialize_fast_strings5                159.48%   127.98us     7.81K
unsafe_deserialize_arrays                                 158.01us     6.33K
unsafe_deserialize_fast_arrays                  222.55%    71.00us    14.08K
unsafe_deserialize_nestedArrays                           231.72us     4.32K
unsafe_deserialize_fast_nestedArrays            165.38%   140.11us     7.14K
unsafe_deserialize_maps                                   396.14us     2.52K
unsafe_deserialize_fast_maps                    320.59%   123.56us     8.09K
unsafe_deserialize_structs                                148.35us     6.74K
unsafe_deserialize_fast_structs                 135.53%   109.46us     9.14K
```

2025-01-16 03:04 UTC, jinchengchenghh commented
Run the totally benchmark
```
/mnt/DP_disk1/code/velox/build/velox/row/benchmarks# ./velox_unsafe_row_serialize_benchmark
============================================================================
[...]marks/UnsafeRowSerializeBenchmark.cpp     relative  time/iter   iters/s
============================================================================
unsafe_serialize_fixedWidth5                               50.08us    19.97K
compact_serialize_fixedWidth5                              26.03us    38.42K
container_serialize_fixedWidth5                           150.15us     6.66K
unsafe_deserialize_fixedWidth5                            107.93us     9.27K
unsafe_deserialize_fast_fixedWidth5             248.93%    43.36us    23.06K
compact_deserialize_fixedWidth5                            35.01us    28.56K
container_deserialize_fixedWidth5                         129.72us     7.71K
unsafe_serialize_fixedWidth10                             123.41us     8.10K
compact_serialize_fixedWidth10                             51.83us    19.30K
container_serialize_fixedWidth10                          290.12us     3.45K
unsafe_deserialize_fixedWidth10                           123.29us     8.11K
unsafe_deserialize_fast_fixedWidth10            138.77%    88.84us    11.26K
compact_deserialize_fixedWidth10                           53.39us    18.73K
container_deserialize_fixedWidth10                        205.49us     4.87K
unsafe_serialize_fixedWidth20                             172.48us     5.80K
compact_serialize_fixedWidth20                             77.23us    12.95K
container_serialize_fixedWidth20                          457.88us     2.18K
unsafe_deserialize_fixedWidth20                           500.25us     2.00K
unsafe_deserialize_fast_fixedWidth20            198.19%   252.41us     3.96K
compact_deserialize_fixedWidth20                          104.99us     9.52K
container_deserialize_fixedWidth20                        384.62us     2.60K
decimalsSerialize                                          51.42us    19.45K
decimalsDeserialize                                        73.93us    13.53K
unsafe_serialize_strings1                                  36.94us    27.07K
compact_serialize_strings1                                 27.71us    36.09K
container_serialize_strings1                               90.83us    11.01K
unsafe_deserialize_strings1                                54.76us    18.26K
unsafe_deserialize_fast_strings1                153.17%    35.75us    27.97K
compact_deserialize_strings1                               31.88us    31.36K
container_deserialize_strings1                             84.02us    11.90K
unsafe_serialize_strings5                                 103.82us     9.63K
compact_serialize_strings5                                 78.93us    12.67K
container_serialize_strings5                              413.64us     2.42K
unsafe_deserialize_strings5                               104.09us     9.61K
unsafe_deserialize_fast_strings5                103.84%   100.24us     9.98K
compact_deserialize_strings5                              139.13us     7.19K
container_deserialize_strings5                            236.07us     4.24K
unsafe_serialize_arrays                                    72.52us    13.79K
compact_serialize_arrays                                   58.26us    17.17K
container_serialize_arrays                                145.92us     6.85K
unsafe_deserialize_arrays                                  85.43us    11.70K
unsafe_deserialize_fast_arrays                  235.67%    36.25us    27.59K
compact_deserialize_arrays                                 26.44us    37.82K
container_deserialize_arrays                              137.58us     7.27K
unsafe_serialize_nestedArrays                             329.86us     3.03K
compact_serialize_nestedArrays                            275.41us     3.63K
container_serialize_nestedArrays                          591.96us     1.69K
unsafe_deserialize_nestedArrays                           283.85us     3.52K
unsafe_deserialize_fast_nestedArrays            210.22%   135.03us     7.41K
compact_deserialize_nestedArrays                          107.86us     9.27K
container_deserialize_nestedArrays                        484.08us     2.07K
unsafe_serialize_maps                                     287.61us     3.48K
compact_serialize_maps                                    236.49us     4.23K
container_serialize_maps                                    2.08ms    481.83
unsafe_deserialize_maps                                   425.68us     2.35K
unsafe_deserialize_fast_maps                    290.92%   146.32us     6.83K
compact_deserialize_maps                                  101.10us     9.89K
container_deserialize_maps                                341.35us     2.93K
unsafe_serialize_structs                                   77.17us    12.96K
compact_serialize_structs                                  74.01us    13.51K
container_serialize_structs                               206.36us     4.85K
unsafe_deserialize_structs                                110.84us     9.02K
unsafe_deserialize_fast_structs                 186.71%    59.37us    16.84K
compact_deserialize_structs                                45.18us    22.13K
container_deserialize_structs                             186.85us     5.35K
```

2025-02-27 16:55 UTC, jinchengchenghh commented
Hi, @mbasmanova Can you help review this PR? Much thanks!

2025-03-06 03:00 UTC, mbasmanova commented
@jinchengchenghh Curious, where / how do you use UnsafeRow serde?

2025-03-06 03:05 UTC, mbasmanova commented on velox/row/UnsafeRowFast.cpp
> +readFixedWidthValue(const char* buffer, T* rawValue, vector_size_t index) {
Wondering how much of this is a copy-paste from UnsafeRowDeserializers? Any particular reason you are not deleting UnsafeRowDeserializers?

2025-03-06 03:07 UTC, mbasmanova commented on velox/row/tests/UnsafeRowFuzzTest.cpp
> +          UnsafeRowFast::deserialize(serialized, rowType, pool_.get());
Are we no longer testing UnsafeRowDeserializer?

2025-03-06 10:03 UTC, jinchengchenghh commented on velox/row/UnsafeRowFast.cpp
> +readFixedWidthValue(const char* buffer, T* rawValue, vector_size_t index) {
Just for the benchmark, if you think this implement is ok, I will drop the UnsafeRowDeserializers in the following commit in this PR.

2025-03-06 10:04 UTC, jinchengchenghh commented on velox/row/tests/UnsafeRowFuzzTest.cpp
> +          UnsafeRowFast::deserialize(serialized, rowType, pool_.get());
yes, we will drop it.

2025-03-06 10:07 UTC, jinchengchenghh commented
When we return the result to Spark, we need the RowVector to row, especially the fallback case, return row to Spark operators and convert row to Vector as velox task input in the next stage

2025-03-06 10:35 UTC, mbasmanova commented on velox/row/UnsafeRowFast.cpp
> +readFixedWidthValue(const char* buffer, T* rawValue, vector_size_t index) {
Sounds good. To ease landing, would it be possible to keep the old API, but replace implementation by calling the new API?

2025-03-06 10:36 UTC, mbasmanova commented
CC: @kKPulla

2025-03-06 10:37 UTC, mbasmanova commented
@kKPulla Kk, would you help review this PR?

2025-03-06 15:23 UTC, kKPulla commented
> @kKPulla Kk, would you help review this PR?

For sure. @jinchengchenghh I will review it this week and get back with any comments.

2025-03-17 17:49 UTC, kKPulla requested changes
Lgtm functionally, pending comments about API backwards compatibility. 

cc: @pedroerp  or @xiaoxmeng if you have any comments/thoughts.

2025-03-17 17:49 UTC, kKPulla commented on velox/row/UnsafeRowFast.cpp
> +readFixedWidthValue(const char* buffer, T* rawValue, vector_size_t index) {
+1 to Masha's comment about keeping the old API. I do see a bunch of usage of the existing API internally at Meta and I would assume the case externally too. 

Unless we changed the serialization format (which I don't think we did based on my code read), they can be merged this way right?

2025-03-17 17:49 UTC, kKPulla commented on velox/row/tests/UnsafeRowFuzzTest.cpp
> +          UnsafeRowFast::deserialize(serialized, rowType, pool_.get());
If we are merging them as mentioned above, this should be a no-op but if we are keeping both impl, then let's keep both as fast and slow path tests.

2025-03-18 17:24 UTC, kKPulla approved these changes
Lgtm, thanks for making the change in a backwards compatible way. Please address the format check signal failure before merging.

Note: The build failures you are seeing are likely related to [PR](https://github.com/facebookincubator/velox/pull/12695) (cc: @xiaoxmeng ) Let's wait on getting all green signals before merging this

2025-03-25 12:02 UTC, closed without merging