Add uuid function for prestosql
facebookincubator/velox pull request #1737
Opened 2022-05-30 09:53 UTC by leoluan2009

Add uuid function for prestosql

2022-06-01 02:48 UTC, leoluan2009 commented
> Thanks for this function. Please add relevant function documentation in velox/docs/functions folder.
> 
> It seems like Presto has a high-level page for this function at https://prestodb.io/docs/current/functions/uuid.html?highlight=uuid, so adding a new rst file is fine.

Do we need to add uuid type like presto?

2022-06-04 20:31 UTC, aditi-pandit commented
> > Thanks for this function. Please add relevant function documentation in velox/docs/functions folder.
> > It seems like Presto has a high-level page for this function at https://prestodb.io/docs/current/functions/uuid.html?highlight=uuid, so adding a new rst file is fine.
> 
> Hi @aditi-pandit Do we need to add uuid type like presto?

I think we should ideally.

Masha (@mbasmanova), Pedro (@pedroerp), wdyt ?

2022-06-06 15:41 UTC, mbasmanova requested changes
@leoluan2009 Some comments below. By convention, PRs that add function should use a title formatted as "Add uuid Presto function".

2022-06-06 15:41 UTC, mbasmanova commented on velox/functions/prestosql/Uuid.h
> +    result.setNoCopy(StringView(uuid_string));
Why are you using setNoCopy? I think this function must copy the string, otherwise, the StringView will point to freed memory.

2022-06-06 15:41 UTC, mbasmanova commented on velox/docs/functions/uuid.rst
> +   Returns a pseudo randomly generated UUID as a single character string
The signature and semantics must match Presto SQL exactly, hence, it needs to return a value of type UUID, not VARCHAR.

2022-09-19 17:56 UTC, closed without merging