Install fbthrift
facebookincubator/velox pull request #1768
Opened 2022-06-05 21:35 UTC by yingsu00

Thrift library is required for the new native Parquet reader. This
commit installs fbthrift for Velox.

2022-06-05 21:41 UTC, yingsu00 commented
Note: I don't seem to have permission to create an archive snapshot of fbthrift in github, so I directly included the installation block in `()`  in setup-circleci.sh:
```
+(
+  git clone https://github.com/facebook/fbthrift &&
+  cd fbthrift &&
+  git checkout $FB_OS_VERSION &&
+  cd build &&
+  cmake -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS" -DBUILD_TESTS=OFF .. &&
+  make "-j$(nproc)" &&
+  make install
+)
```
 @kgpai @mshang816 do you have permission to do that? Or is it ok to use the code in `() ` block?

2022-06-09 23:23 UTC, Yuhta requested changes
We must have `apache-thrift` instead of `fbthrift` here to avoid any potential conflicts with arrow

2022-06-09 23:30 UTC, kgpai commented
Hi Ying, 
Just saw this, apart from the points that @Yuhta  raises. Installing of fbthrift (or apache-thrift) isnt required for VELOX MINIMAL. Both these libraries must only be installed if parquet is required and we shouldnt enforce installation of this for torcharrow etc. 
I think something similar to S3 dependencies can be done and have these gated only for PARQUET .

2022-06-09 23:32 UTC, kgpai requested changes

2022-06-09 23:32 UTC, kgpai commented on scripts/setup-macos.sh
> -MACOS_DEPS="ninja cmake ccache protobuf icu4c boost gflags glog libevent lz4 lzo snappy xz zstd openssl@1.1"
Lets not add additional dependencies for base macos install. We are in the process of moving most of these out of brew as  libraries installed this way cannot be cross compiled.

2022-06-10 08:00 UTC, yingsu00 commented
@kgpai @Yuhta Thank you very much for your valuable feedbacks. The Thrift lib for Parquet reader doesn't have to be fbthrift, and apache thrift would also work. I just copied the fbthrift installation from presto_cpp library. I'll update this PR with your dependency comments addressed.

2022-06-15 02:54 UTC, yingsu00 commented
> Hi Ying, Just saw this, apart from the points that @Yuhta raises. Installing of fbthrift (or apache-thrift) isnt required for VELOX MINIMAL. Both these libraries must only be installed if parquet is required and we shouldnt enforce installation of this for torcharrow etc. I think something similar to S3 dependencies can be done and have these gated only for PARQUET .

@kgpai Hi Krishna, I'm not sure if this is possible. The set up script would be ran before calling make. The user can set VELOX_BUILD_MINIMAL to true after running setup-macos.sh and then run make. Did you mean to make CMake install these dependencies? Shall we make apache/thrift as a submodule instead?

2022-07-17 21:10 UTC, yingsu00 commented
No longer needed as Arrow would include thrift

2022-07-17 21:10 UTC, closed without merging