Implement MarkDistinctOperator
facebookincubator/velox pull request #2321
Opened 2022-08-18 07:05 UTC by shiyu-bytedance

2022-08-18 07:08 UTC, shiyu-bytedance commented
@mbasmanova hello again, I implemented MarkDistinctNode and would like to contribute to velox.

2022-08-18 15:02 UTC, kagamiori commented
Hi @shiyu-bytedance, Glad to have your contribution! Could you add a description to this PR about what this operator does and why it is needed? Thanks!

2022-08-18 19:48 UTC, shiyu-bytedance commented
> 

Done. https://github.com/facebookincubator/velox/pull/2321#issue-1342651362

2022-08-18 20:40 UTC, aditi-pandit reviewed
Thanks @shiyu-bytedance for this code. Took a quick look at your code. Overall looks okay. Had some questions.

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/tests/utils/PlanBuilder.h
> +
Please remove newline.

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/tests/utils/PlanBuilder.h
> +      const std::vector<std::shared_ptr<const core::FieldAccessTypedExpr>>&
Use alias "FieldAccessTypedExprPtr"

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/tests/utils/PlanBuilder.h
> +          distinctVariables);
Rename "distinctFIelds" ?

2022-08-18 20:40 UTC, aditi-pandit commented on velox/core/PlanNode.h
> +      const std::vector<std::shared_ptr<const FieldAccessTypedExpr>>&
Use alias "FieldAccessTypedExprPtr"

2022-08-18 20:40 UTC, aditi-pandit commented on velox/core/PlanNode.h
> +          distinctVariables,
Nit : Rename distinctFields. Change this naming uniformly across this class.

2022-08-18 20:40 UTC, aditi-pandit commented on velox/core/PlanNode.h
> +  getDistinctVariables() const {
Why did you use ITYpedExpr here instead of FIeldAccessTypedExpr ?

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/LocalPlanner.cpp
> +      std::vector<uint32_t> channels = toChannels(
We can do this logic inside the constructor of the MarkDistinct operator. The distinct fields can be directly obtained from the PlanNode there, so there isn't a need for the extra variable for the input channels.

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/CMakeLists.txt
> +  AssignUniqueId.cpp
This file is already present as the last entry in the list. Please remove it.

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/MarkDistinct.cpp
> +  VectorPtr& result = results_[0];
It seems this logic is looking for distinct rows within this input buffer itself. I thought we would need to look globally. Are you assuming that the input is sorted so a local check is sufficient ?

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/MarkDistinct.h
> +  std::unordered_set<uint64_t> hashSet_;
Please can you add comments for the meaning of these fields.

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/tests/CMakeLists.txt
> +  AssignUniqueIdTest.cpp
This test is present towards the beginning of this list. Please remove this entry.

2022-08-18 20:40 UTC, aditi-pandit commented on velox/exec/tests/MarkDistinctTest.cpp
> +      return makeFlatVector<NativeType>(
Please can you add more tests that cover multiple batches of input rows.

2022-08-18 21:28 UTC, aditi-pandit commented on velox/exec/MarkDistinct.cpp
> +  VectorPtr& result = results_[0];
Nvm... Noticed that your hashSet_ structure is global so should take care of this. Please add relevant comments about all these member variables in the .h file for this.

2022-08-22 19:51 UTC, mbasmanova requested changes
@shiyu-bytedance Shiyu, thank you for adding a new operator. Please, add it to documentation: velox/docs/develop/operators.rst

Aditi left some good comments. I added a few more.

2022-08-22 19:51 UTC, mbasmanova commented on velox/core/PlanNode.cpp
> +  // Nothing to add.
Shouldn't we specify the "distinctVariables" here?

2022-08-22 19:51 UTC, mbasmanova commented on velox/exec/MarkDistinct.h
> +  std::unordered_set<uint64_t> hashSet_;
Any particular reason not to use VectorHasher and a HashTable? hashSet is slow.

2022-08-22 19:51 UTC, mbasmanova commented on velox/exec/MarkDistinct.cpp
> +    if (hashSet_.find(hash) == hashSet_.end()) {
What about hash collisions?

2022-08-22 19:51 UTC, mbasmanova commented on velox/exec/tests/utils/PlanBuilder.h
> +      const std::vector<std::shared_ptr<const core::FieldAccessTypedExpr>>&
Please, document this method and change input to std::vector<std::string> to allow for passing column names like in other methods.

2022-12-04 20:52 UTC, closed without merging