Print output vector failed
facebookincubator/velox pull request #3531
Opened 2022-12-16 09:15 UTC by jinchengchenghh

I get the error when running this test.
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AggregationTest
[ RUN      ] AggregationTest.aggregateOfStructNulls
[ROW ROW<b:ROW<c:DOUBLE>,a0:BIGINT>: 1 elements, no nulls]
E1216 16:42:16.781491 637970 Exceptions.h:68] Line: /mnt/DP_disk1/code/velox/./velox/vector/BaseVector.h:139, Function:isNullAt, Expression: isIndexInRange(idx) , Source: RUNTIME, ErrorCode: INVALID_STATE
unknown file: Failure
C++ exception with description "Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Retriable: False
Expression: isIndexInRange(idx)
Function: isNullAt
File: /mnt/DP_disk1/code/velox/./velox/vector/BaseVector.h
Line: 139
Stack trace:

2022-12-16 11:49 UTC, mbasmanova commented
@jinchengchenghh This is expected. The vector size is 1. There is only 1 rows. Accessing row 0 is allowed, but accessing non-existent row 1 will fail. Changing row index from 1 to 0 will fix this.

```
    std::cout << vector->toString() << std::endl;
    std::cout << vector->toString(0) << std::endl;

[ROW ROW<b:ROW<c:DOUBLE>,a0:BIGINT>: 1 elements, no nulls]
{{null}, 1}
```

2022-12-19 03:47 UTC, jinchengchenghh commented
Yes, it works. Thanks. Maybe we can check the index in function start line

2022-12-19 18:44 UTC, mbasmanova requested changes
@jinchengchenghh I suggest instead to improve existing error message

```
VELOX_DCHECK(isIndexInRange(idx));

E1216 16:42:16.781491 637970 Exceptions.h:68] Line: /mnt/DP_disk1/code/velox/./velox/vector/BaseVector.h:139, Function:isNullAt, Expression: isIndexInRange(idx) , Source: RUNTIME, ErrorCode: INVALID_STATE
```

Here, is how this can be done:

```
  virtual bool isNullAt(vector_size_t idx) const {
    VELOX_DCHECK_GE(idx, 0, "Row number is out of range");
    VELOX_DCHECK_LT(idx, length_, "Row number is out of range");
    return rawNulls_ ? bits::isBitNull(rawNulls_, idx) : false;
  }
```

2022-12-20 01:15 UTC, jinchengchenghh commented
`isNullAt` is used in execution pipeline, so it must use `VELOX_DCHECK`? How do you think function toString in release version also need this check ?

2022-12-20 14:08 UTC, mbasmanova commented
@jinchengchenghh toString() should be used only for testing and debugging. I think it is Ok if the check is debug-only. What's the use case for using toString in a release build?

2022-12-21 01:13 UTC, jinchengchenghh commented
Because debug version is too slow, so I always compile RelWithDebInfo version, and use toString() to debug. I'm not sure if it is just my case.

2022-12-21 01:27 UTC, mbasmanova commented
> Because debug version is too slow, so I always compile RelWithDebInfo version, and use toString() to debug. I'm not sure if it is just my case.

I'm surprising that this works. Debugging release version is super hard because there are no symbols.

2022-12-21 01:36 UTC, jinchengchenghh commented
We use java jni call, it is not stable to debug by gdb. So we use print to debug sometimes. And core dump file which is generated by RelWithDebInfo build has symbols, it is enough at most case.

2022-12-21 06:21 UTC, mbasmanova commented
@jinchengchenghh Thank you for clarifying. One option is to (1) improve the error messages in debug mode for isNullAt like suggested earlier; (2) add same non-debug checks to all implementations of XxxVector::toString.

2022-12-22 05:46 UTC, jinchengchenghh commented
@mbasmanova Thanks for your kind review. I have fixed with option 2

2022-12-22 14:25 UTC, mbasmanova requested changes
@jinchengchenghh Some comments below. Also, please fix the check in isNullAt as well.

2022-12-22 14:25 UTC, mbasmanova commented on velox/vector/BaseVector.cpp
> +  VELOX_CHECK(
Use VELOX_CHECK_LT for better error message.

Do not use fmt::format to avoid generating a string in happy case.

2022-12-22 14:28 UTC, mbasmanova commented
@jinchengchenghh Would you update PR description to provide an example of the new error message?

2023-01-03 05:54 UTC, jinchengchenghh commented
Fixed. All test passed except circleci, but I don't think it is caused by my PR

2023-01-03 16:26 UTC, mbasmanova approved these changes
@jinchengchenghh Looks good to me. Please, rebase to latest main so I can merge.

2023-01-03 17:24 UTC, kagamiori commented on velox/vector/tests/VectorToStringTest.cpp
> +  ASSERT_THROW(flat->toString(4), VeloxException);
Hi Jin, Thank you for improving the error messages. Could we check that the new error message does contain the index and valid range as expected in this test?

2023-01-04 04:51 UTC, closed without merging