Fix unstable sorted result
facebookincubator/velox pull request #3716
Opened 2023-01-16 08:42 UTC by zhixingheyi-tian

Issue is exposed from https://github.com/oap-project/gluten/issues/858

2023-01-16 08:44 UTC, zhixingheyi-tian commented
cc @mbasmanova @Yuhta

2023-01-16 15:04 UTC, Yuhta commented
Thanks for the fix, can you add a unit test so that people won't break it again?

2023-01-17 14:37 UTC, mbasmanova requested changes
@zhixingheyi-tian Would you update the PR title and description to explain the issue and the solution? See [How to Write Better Git Commit Messages – A Step-By-Step Guide](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/) and [How to Write a Git Commit Message](https://cbea.ms/git-commit/) to learn more about how to write good descriptions.

As @Yuhta already requested, please, add a test case to reproduce the problem and confirm the fix.

2023-02-08 13:27 UTC, zhixingheyi-tian commented
> Thanks for the fix, can you add a unit test so that people won't break it again?

Hi @Yuhta， I‘d like to add UT. Also  I have one testing case. But seem hard to add the case based existing “runTest” framework：https://github.com/oap-project/velox/blob/0cac96be4b2f9e56eadc9c32598f90f85c230617/velox/exec/tests/OrderByTest.cpp#L156-L191

Is there any other good way to verify output result and expected result.

Thanks.

2023-02-08 13:41 UTC, mbasmanova commented
@zhixingheyi-tian 

> seem hard to add the case

Let's start by updating the PR description to explain the issue and the solution. What is hard about adding a test case?

2023-02-08 15:41 UTC, Yuhta commented
@zhixingheyi-tian I guess you just need `assertQueryOrdered` here.  It takes the plan and compare it with the result from DuckDB.

2023-02-09 01:32 UTC, zhixingheyi-tian commented
> @zhixingheyi-tian
> 
> > seem hard to add the case
> 
> Let's start by updating the PR description to explain the issue and the solution. What is hard about adding a test case?

Issue is **https://github.com/oap-project/gluten/issues/858**.  Have added on the top conversation when creating this PR.
Also will enrich the description.

2023-02-09 14:01 UTC, mbasmanova commented
@zhixingheyi-tian It is not sufficient to link to an issue in a different project. Would you please summarize the problem here as well?

2023-02-10 05:59 UTC, zhixingheyi-tian commented
> @zhixingheyi-tian I guess you just need `assertQueryOrdered` here. It takes the plan and compare it with the result from DuckDB.

Have added the UT.

Thanks,

2023-02-10 06:20 UTC, zhixingheyi-tian commented
> @zhixingheyi-tian It is not sufficient to link to an issue in a different project. Would you please summarize the problem here as well?

Hi @mbasmanova 

Have enriched the description on the top of the conversation.

2023-02-10 11:18 UTC, mbasmanova commented
@zhixingheyi-tian Thank you for describing the issue. I do not think it is a bug, but rather expected behavior. There are no guarantees about preserving the order of input rows in OrderBy. The only guarantee is that output is sorted on the order-by keys.

2023-05-25 14:46 UTC, closed without merging