Add "hashless" partial aggregation
facebookincubator/velox pull request #4157
Opened 2023-02-28 21:36 UTC by shiyu-bytedance

Add logic to detect cardinality changes in input vectors to HashAggregation. When cardinality is high, disable "hash grouping" of input rows, which can take time due to clearing tags array of hashtable.

2023-03-02 16:32 UTC, Yuhta commented on velox/exec/GroupingSet.cpp
> +  char* groups[input_size];
Will this uses up the stack space?  Maybe using a buffer allocated by memory pool is safer.

2023-03-02 16:32 UTC, Yuhta commented on velox/exec/GroupingSet.cpp
> +  vector_size_t row_index[input_size];
Same here, consider using a buffer

2023-03-02 16:32 UTC, Yuhta commented on velox/exec/GroupingSet.cpp
> +  const vector_size_t input_size = activeRows_.countSelected();
Change to camel case to be consistent with the coding style

2023-03-02 16:32 UTC, Yuhta commented on velox/exec/GroupingSet.cpp
> +    aggregates_[i]->addRawInput(groups, activeRows_, tempVectors_, mayPushdown);
Should we keep the pushdown condition same as others (`mayPushdown_[i] && areAllLazyNotLoaded(tempVectors_)`)?

2023-03-02 17:14 UTC, mbasmanova requested changes
Let's consider the design described in https://github.com/facebookincubator/velox/issues/3194#issuecomment-1448012011 and make sure masked aggregations are supported.

2023-03-03 00:16 UTC, shiyu-bytedance commented
> Let's consider the design described in [#3194 (comment)](https://github.com/facebookincubator/velox/issues/3194#issuecomment-1448012011) and make sure masked aggregations are supported.

@mbasmanova to clarify, are there existing use cases of the masked aggregation code paths? Upon implementing MarkDistinct operator, I came to be under the understanding that masked aggregations are in production used exclusively with a HashAggregate operator is preceeded by a MarkDistinct operator, which produces the mask channels.

2023-03-03 01:22 UTC, mbasmanova commented
> are there existing use cases of the masked aggregation code paths?

@shiyu-bytedance Yes, we see such plans in production workload.

2023-03-03 22:02 UTC, shiyu-bytedance commented
> Let's consider the design described in [#3194 (comment)](https://github.com/facebookincubator/velox/issues/3194#issuecomment-1448012011) and make sure masked aggregations are supported.

@mbasmanova to clarify, are you suggesting to ditch the current PR design of going through GroupingSet(and indirectly hashtable without hashing) and re-write the passthrough by introducing new vector API's?

2023-03-07 16:17 UTC, mbasmanova commented
> @mbasmanova to clarify, are you suggesting to ditch the current PR design of going through GroupingSet(and indirectly hashtable without hashing) and re-write the passthrough by introducing new vector API's?

That's right. We do not need to serialize and deserialize grouping keys in case of pass-thru and some aggregate functions (sum, min, max) do not need to perform any conversion from raw inputs to single-value intermediate results.

2023-03-07 20:58 UTC, shiyu-bytedance commented
> > @mbasmanova to clarify, are you suggesting to ditch the current PR design of going through GroupingSet(and indirectly hashtable without hashing) and re-write the passthrough by introducing new vector API's?
> 
> That's right. We do not need to serialize and deserialize grouping keys in case of pass-thru and some aggregate functions (sum, min, max) do not need to perform any conversion from raw inputs to single-value intermediate results.

I agree with you about the new vector API approach being superior. However, from benchmark, we see that most of the slowness come from clearing the tag vector of hashtable and this current implementation that goes through GroupingSet already yields clear performance improvement by eliminating this bottleneck.

Given the interest in this improvement from the ticket, its demonstrable gain and uncertainty around funding a new vector API, I wonder whether we would consider letting this current design move forward so that gluten and ahana could test out the improvement and gauge if this is the right direction we should fund and schedule the new vector API work as a further improvement?

2023-03-07 21:13 UTC, mbasmanova commented
> uncertainty around funding a new vector API

@shiyu-bytedance What does that mean? Would you clarify?

2023-03-07 22:19 UTC, shiyu-bytedance commented
> > uncertainty around funding a new vector API
> 
> @shiyu-bytedance What does that mean? Would you clarify?

I mean that a new vector API will not be 

> > uncertainty around funding a new vector API
> 
> @shiyu-bytedance What does that mean? Would you clarify?

I meant I'm not sure about the scope of work for the new API design and was worried that it may not be implemented in a short time frame.

2023-03-07 22:55 UTC, mbasmanova commented
> I meant I'm not sure about the scope of work for the new API design and was worried that it may not be implemented in a short time frame.

Let's consider the proposed design. I do not expect it to be hard or time consuming to implement.

2023-03-27 07:47 UTC, shiyu-bytedance commented on velox/functions/sparksql/aggregates/LastAggregate.cpp
> +        baseVector->setNull(i, true);
This is an existing bug in current LastAggregate implementation exposed by this change.

2023-03-27 08:19 UTC, shiyu-bytedance commented
> > Let's consider the design described in [#3194 (comment)](https://github.com/facebookincubator/velox/issues/3194#issuecomment-1448012011) and make sure masked aggregations are supported.

For masked aggregations, I think it might be tricky. In the pass though case, what ought to be the intermediate output for a row that is masked out? My intuition is it should be the value equal to as if InitializeNewGroup and extractAccumulator are called (without addRawInput in between).

2023-03-27 17:36 UTC, mbasmanova commented on velox/functions/sparksql/aggregates/LastAggregate.cpp
> +        baseVector->setNull(i, true);
@shiyu-bytedance Got it. Would you file a GitHub issue to describe the bug and submit a separate PR to fix it?

2023-03-28 01:43 UTC, mbasmanova commented
@shiyu-bytedance 

> we add a new exec::Aggregate::convertRawToIntermediate base function and then implement it in all existing aggregate subclasses. 

This is correct. I was thinking that we can provide a default implementation that uses existing APIs as well. This way we do not have to implement the new API for all existing functions at once.

> For masked aggregations, I'm curious, in the case of hashing disabled, what ought to be the intermediate output for a row that is masked out? My intuition is it should be the value equal to as if InitializeNewGroup and extractAccumulator are called (without addRawInput in between). Alternatively, I suppose it might also work if we use NULL as the intermediate output.

Your intuition is correct, I think. Using NULL unconditionally may not work as some aggregate functions (count, count_if) return non-null values even when there are no input rows. I think we need to pass SelectivityVector to the new API to indicate which rows are masked and which are not.

2023-04-14 13:45 UTC, mbasmanova commented
@shiyu-bytedance PR #4588 implements the design we discussed.

2023-04-18 02:07 UTC, shiyu-bytedance commented
> @shiyu-bytedance PR #4588 implements the design we discussed.

got it, thanks!

2023-07-31 07:50 UTC, closed without merging