add presto current_date function
facebookincubator/velox pull request #4664
Opened 2023-04-19 17:25 UTC by liujiayi771

Add current_date presto funtcion, https://github.com/facebookincubator/velox/issues/4663

2023-04-20 03:47 UTC, liujiayi771 commented
@mbasmanova Could you help review this fuction? I'm confused that Spark Fuzzer Tests failed, but it seems to have nothing to do with the function I added.

2023-04-20 05:20 UTC, mbasmanova requested changes
@liujiayi771 Please, check out https://github.com/facebookincubator/velox/blob/main/CONTRIBUTING.md#prestos-sql-functions and https://github.com/facebookincubator/velox/blob/main/CODING_STYLE.md and update the code to compile.

2023-04-20 05:20 UTC, mbasmanova commented on velox/docs/functions/presto/datetime.rst
> +.. function:: current_date() -> date
Please, move this function to preserve alphabetical order.

2023-04-20 05:20 UTC, mbasmanova commented on velox/functions/prestosql/DateTimeFunctions.h
> +  FOLLY_ALWAYS_INLINE bool call(Date& result) {
Use 'void' for return type.

2023-04-20 05:20 UTC, mbasmanova commented on velox/functions/prestosql/DateTimeFunctions.h
> +  // return the current local date
This comment is redundant. Please, remove.

2023-04-20 05:20 UTC, mbasmanova commented on velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp
> +  str << std::put_time(std::localtime(&time), "%Y-%m-%d");
This test may be flaky when running at the very last second of the day.

2023-04-20 15:48 UTC, liujiayi771 commented
> @liujiayi771 Please, check out https://github.com/facebookincubator/velox/blob/main/CONTRIBUTING.md#prestos-sql-functions and https://github.com/facebookincubator/velox/blob/main/CODING_STYLE.md and update the code to compile.

Thanks. In addition to the issues mentioned above, I made some other modifications. current_date should obtain the corresponding date according to the timezone in session properties, and I also modified the test to avoid mistake when running at the very last second of the day.

2023-04-20 20:14 UTC, mbasmanova reviewed
@liujiayi771 Thank you for updating the PR. Looks good % a small nit.

2023-04-20 20:14 UTC, mbasmanova commented on velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp
> +  auto mockRowVector =
Do not use term 'mock'.

```
auto emptyRowVector = makeRowVector(ROW(), 1);
```

2023-04-20 20:15 UTC, mbasmanova commented on velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp
> +  setQueryTimeZone(tz);
Perhaps, add a test when tz is not set, e.g. verify code path where timeZone_ is nullptr.

2023-04-21 18:57 UTC, aditi-pandit commented
@mbasmanova : I have a higher level question about this function. The expectation is that it returns the date at the start of the query. If this function gets called multiple times during the execution it is expected to return the same result. 

This implementation doesn't keep those semantics in mind and we need to make enhancements at the Velox framework level for it.

wdyt ?

2023-04-25 19:23 UTC, mbasmanova commented
@aditi-pandit This function call should be processed at the start of execution by constant-folding, hence, it should produce same result for all rows.

2023-04-25 19:27 UTC, mbasmanova commented on velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp
> +  auto tp0 = std::chrono::system_clock::now();
variable names a1, a2, a3 are anti-pattern; please, rename; it may be helpful to split this test into 2: with and without timezone specified.

2023-04-25 19:27 UTC, mbasmanova commented on velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp
> +  auto zonedTime1 = date::make_zoned(tz, std::chrono::system_clock::now());
The code to get a Date for now() repeats a few time. Consider introducing a small helper function to reduce copy-paste and improve readability.

2023-04-25 22:39 UTC, aditi-pandit commented
> @aditi-pandit This function call should be processed at the start of execution by constant-folding, hence, it should produce same result for all rows.

Thanks @mbasmanova. Is there a way to ensure the constant folding behavior is enforced ? Right now, it seems like the side-effect of an optimization in the framework. That is fragile from a framework point of view.

@liujiayi771 : Please also add a unit test for Velox plan invoking current_date in multiple FilterProject operators and validate the result values always match for this function.

2023-04-26 00:56 UTC, aditi-pandit commented
> @aditi-pandit This function call should be processed at the start of execution by constant-folding, hence, it should produce same result for all rows.

@mbasmanova : Had another question about that...Constant-folding would be within the context of a single ExpressionTree. current_date is expected to give the same result if called in 2 different columns in a Project or even in 2 different FilterProject operators in the same plan. That would be outside of the scope of constant folding.

Please can you clarify.

2023-04-26 03:25 UTC, liujiayi771 commented
> > @aditi-pandit This function call should be processed at the start of execution by constant-folding, hence, it should produce same result for all rows.
> 
> Thanks @mbasmanova. Had another question about that...Constant-folding would be within the context of a single ExpressionTree. current_date is expected to give the same result if called in 2 different columns in a Project or even in 2 different FilterProject operators in the same plan. That would be outside of the scope of constant folding I think.
> 
> Please can you clarify.
> 
> @liujiayi771 : Please also add a unit test for Velox plan invoking current_date in multiple FilterProject operators and validate the result values always match for this function.
Thanks for your comments. If the result of current_date can be different in 2 FilterProject operators in the same plan, this is hard to detect in UT, only triggering UT in the last few seconds of the day may encounter this problem. I think it is possible to get different results in different operators. Do we need to transform it to get the start time of plan execution from the session consistent with presto?
However, different SQL engines have different semantics of current_date. If modification is really needed, the current implementation can be moved to sparksql, and spark obtains the current date in real time.

2023-04-26 03:26 UTC, liujiayi771 commented
@aditi-pandit Thanks for your comments. If the result of current_date can be different in 2 FilterProject operators in the same plan, this is hard to detect in UT, only triggering UT in the last few seconds of the day may encounter this problem. I think it is possible to get different results in different operators. Do we need to transform it to get the start time of plan execution from the session consistent with presto?
However, different SQL engines have different semantics of current_date. If modification is really needed, the current implementation can be moved to sparksql, and spark obtains the current date in real time.

2023-04-26 13:11 UTC, mbasmanova commented
@liujiayi771 @aditi-pandit 

> Returns the current date as of the start of the query.

I suggest to return "as of the start of the query" from the documentation of this function. Velox doesn't execute full queries, only fragments and therefore cannot possibly know when the query started.

2023-04-26 15:12 UTC, aditi-pandit commented
> @liujiayi771 @aditi-pandit
> 
> > Returns the current date as of the start of the query.
> 
> I suggest to remove "as of the start of the query" from the documentation of this function. Velox doesn't execute full queries, only fragments and therefore cannot possibly know when the query started.

Thanks @mbasmanova. That sounds good. 

I don't think presto_server will call current_date on the Prestissimo worker at all. But we should try to blacklist this function from a Prestissimo invocation if required.

2023-04-26 15:14 UTC, aditi-pandit commented
> @aditi-pandit Thanks for your comments. If the result of current_date can be different in 2 FilterProject operators in the same plan, this is hard to detect in UT, only triggering UT in the last few seconds of the day may encounter this problem. It's not clear to me whether presto's constant-folding is global.
> 
> However, different SQL engines have different implementations of current_date. If modification is really needed, the current implementation can be moved to sparksql, because spark's implementation just use JDK's LocalDate.now to get the current date.

Thanks @liujiayi771. Like Masha suggested we can remove the "start of the query" requirement (as from Presto) and have different Velox semantics. Presto co-ordinator doesn't invoke this function from Velox anyways.

2023-04-27 00:59 UTC, liujiayi771 commented
> @liujiayi771 @aditi-pandit
> 
> > Returns the current date as of the start of the query.
> 
> I suggest to remove "as of the start of the query" from the documentation of this function. Velox doesn't execute full queries, only fragments and therefore cannot possibly know when the query started.

done.

2023-04-27 14:40 UTC, mbasmanova approved these changes
@liujiayi771 Thanks.

2023-04-30 14:11 UTC, liujiayi771 commented
@mbasmanova Hi, do I need to re-run CI test to let it pass? Or it will be merged automatically.

2023-05-01 14:48 UTC, mbasmanova commented
@liujiayi771 I tried landing last week, but there were some internal failures. Let me try again.

2023-05-01 19:12 UTC, closed without merging