Add unit tests for decimal not-equal functions
facebookincubator/velox pull request #4757
Opened 2023-04-26 23:21 UTC by karteekmurthys

The neq functions are registered as part of this PR https://github.com/facebookincubator/velox/pull/4638.
This change adds some unit tests for neq decimal function.

2023-04-27 23:11 UTC, laithsakka approved these changes

2023-04-27 23:11 UTC, laithsakka commented on velox/functions/prestosql/tests/ComparisonsTest.cpp
> +                           VectorPtr expectedResult,
nit: const VectorPtr& 
nit: const std::vector<VectorPtr>& inputs

2023-04-27 23:11 UTC, laithsakka commented
Looks good just a small nit

2023-04-28 04:45 UTC, karteekmurthys commented on velox/functions/prestosql/tests/ComparisonsTest.cpp
> +                           VectorPtr expectedResult,
Done.

2023-04-28 05:11 UTC, majetideepak commented
@karteekmurthys can we hold on to merging this PR until this  https://github.com/facebookincubator/velox/pull/4434 lands?
Thanks.

2023-04-28 05:12 UTC, majetideepak requested changes
Would like to block this PR until https://github.com/facebookincubator/velox/pull/4434 lands.

2023-04-28 05:25 UTC, majetideepak commented
The reason to block is that https://github.com/facebookincubator/velox/pull/4434 implements decimal type as a logical type and it impacts all decimal code changes. We want to minimize the diff.

2023-05-12 04:16 UTC, majetideepak approved these changes
@karteekmurthys CI build is failing.

2023-05-12 19:32 UTC, closed without merging