Instrall folly in setup script.
facebookincubator/velox pull request #5222
Opened 2023-06-10 22:24 UTC by amitkdutta

When we build velox with folly dependencies, its required to have folly in system path. Setup script does not call folly build method. As a result, when a change in folly is needed to build velox from main (e.g. https://github.com/facebookincubator/velox/pull/4828), running setup does not make build work because folly is not built with new options (here huge int `-DFOLLY_HAVE_INT128_T=ON`). Making sure we call folly installation from setup script. We can definitely use bundled folly with `folly_SOURCE=BUNDLED make`, however that does not work always.

2023-06-11 00:01 UTC, aditi-pandit commented
Thanks @amitkdutta. I too hit this yesterday.

2023-06-11 17:19 UTC, kgpai approved these changes

2023-06-11 17:22 UTC, kgpai commented
FYI , this isn’t strictly required for Mac builds as you can always affix folly_SOURCE=BUNDLED to ensure folly is built with the right flags .

2023-06-11 19:39 UTC, majetideepak requested changes
The fix should be to default to the bundled installation as @kgpai suggested.
The install scripts are not ideal as users have to manually reinstall when needed such as the int128 case. It is not obvious always when the reinstall has to happen.

2023-06-12 16:17 UTC, amitkdutta commented
@majetideepak @kgpai Default folly installation does not build velox. This is the command we run: ` folly_SOURCE=BUNDLED make`  It fails in my laptop and a few others with following error:

-- Found libevent: /usr/local/lib/libevent.dylib
CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2d", but
  required is at least "1.1.1" (found
  /opt/homebrew/Cellar/openssl/1.0.2d_1/lib/libcrypto.dylib, )
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindOpenSSL.cmake:670 (find_package_handle_standard_args)
  _build/release/_deps/folly-src/CMake/folly-deps.cmake:81 (find_package)
  _build/release/_deps/folly-src/CMakeLists.txt:132 (include)


-- Configuring incomplete, errors occurred!
make[1]: *** [cmake] Error 1
make: *** [release] Error 2
```

2023-06-12 16:45 UTC, majetideepak commented
@amitkdutta System dependencies are hard to deal with when we update them or the system (OS update). Hence the push toward the bundled installation. Expert users can still choose to use system installation if they know when to re-install.
eg: They can invoke the function directly `setup-macos.sh install_folly`
Since these setup scripts are used by non-expert users also, we should not install dependencies system-wide by default.
Can you open an issue to investigate the bundled install failure?

2023-06-12 16:47 UTC, majetideepak commented
>  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2d", but
  required is at least "1.1.1" (found
  /opt/homebrew/Cellar/openssl/1.0.2d_1/lib/libcrypto.dylib, )

The issue also seems to be related to OpenSSL and not folly. Can you check?

2023-06-12 18:36 UTC, majetideepak commented
@amitkdutta can you open an issue with this error and details on your system/environment (arch, OS version etc.)?

2023-06-14 01:09 UTC, gggrace14 commented
> @majetideepak @kgpai Default folly installation does not build velox. This is the command we run: ` folly_SOURCE=BUNDLED make` It fails in my laptop and a few others with following error:
> 
> ```
> -- Found libevent: /usr/local/lib/libevent.dylib
> CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2d", but
>   required is at least "1.1.1" (found
>   /opt/homebrew/Cellar/openssl/1.0.2d_1/lib/libcrypto.dylib, )
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindOpenSSL.cmake:670 (find_package_handle_standard_args)
>   _build/release/_deps/folly-src/CMake/folly-deps.cmake:81 (find_package)
>   _build/release/_deps/folly-src/CMakeLists.txt:132 (include)
> 
> -- Configuring incomplete, errors occurred!
> make[1]: *** [cmake] Error 1
> make: *** [release] Error 2
> ```
> 
> However installing folly system wide works well. Hence the change.

@amitkdutta I have workaround for this error but might not be the right solution. Set the env variable OPENSSL_ROOT_DIR to point to $(brew --prefix openssl@1.1), when you run cmake or in your dev env like CLion. The error is like it finds your other version of openssl. We can set the env variable OPENSSL_ROOT_DIR  explicitly.

2023-06-15 03:04 UTC, kgpai commented
I think we should probably make folly installation a parameter of the script which is by default turned off. There are still several developers who still use installed folly for whatever reason and allowing them the option to install it via a flag should be fine in my opinion. 
@majetideepak @amitkdutta

2023-06-18 00:12 UTC, amitkdutta commented
> I think we should probably make folly installation a parameter of the script which is by default turned off. There are still several developers who still use installed folly for whatever reason and allowing them the option to install it via a flag should be fine in my opinion. @majetideepak @amitkdutta



> > @majetideepak @kgpai Default folly installation does not build velox. This is the command we run: ` folly_SOURCE=BUNDLED make` It fails in my laptop and a few others with following error:
> > ```
> > -- Found libevent: /usr/local/lib/libevent.dylib
> > CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
> >   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
> >   system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2d", but
> >   required is at least "1.1.1" (found
> >   /opt/homebrew/Cellar/openssl/1.0.2d_1/lib/libcrypto.dylib, )
> > Call Stack (most recent call first):
> >   /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
> >   /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindOpenSSL.cmake:670 (find_package_handle_standard_args)
> >   _build/release/_deps/folly-src/CMake/folly-deps.cmake:81 (find_package)
> >   _build/release/_deps/folly-src/CMakeLists.txt:132 (include)
> > 
> > -- Configuring incomplete, errors occurred!
> > make[1]: *** [cmake] Error 1
> > make: *** [release] Error 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However installing folly system wide works well. Hence the change.
> 
> @amitkdutta I have workaround for this error but might not be the right solution. Set the env variable OPENSSL_ROOT_DIR to point to $(brew --prefix openssl@1.1), when you run cmake or in your dev env like CLion. The error is like it finds your other version of openssl. We can set the env variable OPENSSL_ROOT_DIR explicitly.

Thanks @gggrace14. Setting DOPENSSL_ROOT_DIR explicitly works. In CLI, we can do
```
export OPENSSL_ROOT_DIR=$(brew --prefix openssl@1.1)
folly_SOURCE=BUNDLED make
```

In CLION, we need to pass `folly_SOURCE=BUNDLED make` as environment and  `-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1` as CMake Option

2023-06-19 16:34 UTC, majetideepak commented
The setup script `setup-macos.sh` has `OPENSSL_ROOT_DIR=$(brew --prefix openssl@1.1)`. This variable is missing from the bundled cmake file. Let's add it there.

2023-10-01 22:08 UTC, closed without merging