Add to_ieee754_64 Presto Scalar Function
facebookincubator/velox pull request #6445
Opened 2023-09-06 17:53 UTC by pdabre12

Fixes to_ieee754_64 Presto function to return 64 bits instead of 64 bytes.

Fixes: https://github.com/prestodb/presto/issues/20704

2023-09-07 05:42 UTC, aditi-pandit commented on velox/functions/prestosql/tests/BinaryFunctionsTest.cpp
> +  EXPECT_EQ(hexToDec("3FF0000000000000"), toIEEE754Bits64(1.0));
The tests for values 0.0 and 1.0 are repeated.

2023-09-07 17:14 UTC, pdabre12 commented
@aditi-pandit  Fixed the issues.

2023-09-07 22:25 UTC, aditi-pandit commented on velox/functions/prestosql/BinaryFunctions.h
> +    static constexpr auto kTypeLength = sizeof(int64_t);
This code is exactly the same as ToBigEndian64 as above. I would have thought that you have to memcpy the double into a bit array and then do a reverse like the previous code.

2023-09-07 22:28 UTC, aditi-pandit approved these changes
Thanks !

2023-09-07 22:31 UTC, aditi-pandit commented
@Yuhta : Please can you review.

2023-09-07 22:34 UTC, aditi-pandit requested changes
Please run the fuzzer and paste its output https://facebookincubator.github.io/velox/develop/testing/fuzzer.html#how-to-run

2023-09-07 22:51 UTC, pdabre12 commented
@aditi-pandit 

**Fuzzer output for to_ieee754_64 Presto Scalar function:**

I20230907 15:46:38.054050 1173282 ExpressionVerifier.cpp:63] ===================
I20230907 15:46:38.054075 1173282 ExpressionVerifier.cpp:74] All results match.
I20230907 15:46:38.054101 1173282 ExpressionFuzzer.cpp:1358] ==============================> Done with iteration 7776
I20230907 15:46:38.054133 1173282 ExpressionFuzzer.cpp:1093] ==============================> Top 1 by number of rows processed
I20230907 15:46:38.054148 1173282 ExpressionFuzzer.cpp:1095] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230907 15:46:38.054162 1173282 ExpressionFuzzer.cpp:1099] to_ieee754_64 7777 100.00% 125961
I20230907 15:46:38.054184 1173282 ExpressionFuzzer.cpp:1105] ==============================> Bottom 1 by number of rows processed
I20230907 15:46:38.054199 1173282 ExpressionFuzzer.cpp:1107] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230907 15:46:38.054214 1173282 ExpressionFuzzer.cpp:1112] to_ieee754_64 7777 100.00% 125961
I20230907 15:46:38.054231 1173282 ExpressionFuzzer.cpp:1125] ==============================> All stats sorted by number of times the function was chosen
I20230907 15:46:38.054246 1173282 ExpressionFuzzer.cpp:1127] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230907 15:46:38.054261 1173282 ExpressionFuzzer.cpp:1131] to_ieee754_64 7777 100.00% 125961
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.

2023-09-08 01:51 UTC, aditi-pandit approved these changes

2023-09-14 14:07 UTC, closed without merging