Fix Timestamp::toTimezone for negative timestamps.
facebookincubator/velox pull request #6788
Opened 2023-09-28 07:02 UTC by lingbin

The value of `seconds_` in `Timepstamp` is the starting point of one 
second, so when converting a `time_point` from milliseconds to seconds, 
it should always be rounded down.

However, `std::chrono::duration_cast` will always round to 0, so for 
negative numbers (times before 1970-01-01 00:00:00), the result will 
be wrong(will differ from the correct result 1 second).

Correcting the rounding behavior also affects the unit test of 
`date_format`, which is also fixed in this PR.

Fixes #6489 and #6787.

2023-09-28 07:06 UTC, lingbin commented on velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp
> +      "-2000-02-29 05:53:28.987000",
Already checked in Presto, the seconds should be `28`.  
```
presto> select TIMESTAMP '-2000-02-29 00:00:00.987 UTC' AT TIME ZONE 'Asia/Kolkata';
                 _col0
---------------------------------------
 -2000-02-29 05:53:28.987 Asia/Kolkata
(1 row)

```

2023-09-28 07:09 UTC, lingbin commented on velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp
> +      "-2000-02-28 16:07:02.987000",
Already checked in Presto, the seconds should be `02`.

```
presto> select TIMESTAMP '-2000-02-29 00:00:00.987 UTC' AT TIME ZONE 'America/Los_Angeles';
                    _col0
----------------------------------------------
 -2000-02-28 16:07:02.987 America/Los_Angeles
(1 row)
```

2023-09-28 08:28 UTC, lingbin commented
@pedroerp  Could you please help to take a look?

2023-09-28 23:11 UTC, pedroerp approved these changes
Looks good to me, thanks for the quick fix! Are there any other places in this file where we could have a similar rounding issue?

2023-09-30 02:44 UTC, pedroerp commented
FYI, I'll be off until the 16th, but @amitkdutta can help validate and get this merged. Thanks

2023-09-30 17:58 UTC, zacw7 commented
Thanks for the fix and looking into this issue.
I'm not sure if negative timestamp is handled properly in Velox?
https://github.com/prestodb/presto/blob/507ca0c3b9572d8c68ddad57ca9a1eb5d1fa439c/presto-native-execution/presto_cpp/presto_protocol/Base64Util.cpp#L140-L142
```CPP
rawTimestamps[i] = velox::Timestamp(
            rawBuffer[i] / 1000, (rawBuffer[i] % 1000) * 1000000);
```
If `rawBuffer[i]` is negative, while the 2nd arg of `Timestamp` expects an unsigned number as `nanos`, it's very likely for the nanos to overflow after being converted to `uint64_t` and exceed the limit `kMaxNanos = 999'999'999`.
To fix the above, I would assume we also need to offset 1 second to make room to hold nano. I wonder how would that impact this change?

2023-09-30 18:01 UTC, zacw7 requested changes
Thanks for the fix and looking into this issue.
I'm not sure if negative timestamp is handled properly in Velox.
https://github.com/prestodb/presto/blob/507ca0c3b9572d8c68ddad57ca9a1eb5d1fa439c/presto-native-execution/presto_cpp/presto_protocol/Base64Util.cpp#L140-L142
```CPP
rawTimestamps[i] = velox::Timestamp(
            rawBuffer[i] / 1000, (rawBuffer[i] % 1000) * 1000000);
```
If `rawBuffer[i]` is negative, while the 2nd arg of `Timestamp` expects an unsigned number as `nanos`, it's very likely for the negative nanos to overflow after being converted to `uint64_t` and exceed the limit `kMaxNanos = 999'999'999`.
To fix the above, I would assume we also need to offset 1 second to make the nano positive. I wonder how would that impact this change?

2023-10-01 14:40 UTC, lingbin commented
@zacw7  As you pointed out, after checking the logic of `Base64Util` in presto_cpp, I also think that the way of constructing `Timestamp` value in it is wrong. I created a PR(https://github.com/prestodb/presto/pull/21011) to fix this problem, please help to take a look.

2023-10-02 17:21 UTC, zacw7 approved these changes

2023-10-02 17:34 UTC, closed without merging