fast path for storing a string into HashStringAllocator
facebookincubator/velox pull request #7355
Opened 2023-10-31 23:24 UTC by oerling

Making a stream and appending a string and finishing a write to HashStringAllocator takes a long time.  The common use case is an append where there is one free list item that spans the rest of the last arena of the HSA. This makes a fast path for allocating the head of this fre block without first unhooking it from the free list and then putting the tail back there.

Using a test with all unique strings as in

select l_orderkey, l_comment, substr(l_comment, 6), count(*) from lineitem group by 1, 2, 3 order by 1 limit 1;

2023-11-01 15:37 UTC, Yuhta commented on velox/common/memory/HashStringAllocator.cpp
> +    freeRestOfBlock(header, spaceTaken);
Do we need to do `header->next()->clearPreviousFree()` here as well?

2023-11-02 16:17 UTC, Yuhta commented on velox/common/memory/HashStringAllocator.cpp
> +    freeRestOfBlock(header, spaceTaken);
@oerling Actually I don't think you need to separate this case with the first `if` branch.  Just adding `freeRestOfBlock` there, adjust the condition, and remove this branch should be good.

2023-11-03 14:27 UTC, Yuhta commented on velox/common/memory/HashStringAllocator.cpp
> +    freeRestOfBlock(header, spaceTaken);
I see it should be good as it is .  Still could be merged with the first branch though.

2023-11-03 14:29 UTC, Yuhta approved these changes

2023-11-03 21:03 UTC, Yuhta commented on velox/common/memory/HashStringAllocator.cpp
> +  const char* ref = ":3F.QZPrvJj0_GF";
@oerling What is this `ref` string?

2023-11-03 21:12 UTC, Yuhta requested changes

2023-11-03 21:12 UTC, Yuhta commented on velox/common/memory/HashStringAllocator.cpp
> +      if (header) {
@oerling `if (!header)`?

2023-11-06 19:56 UTC, closed without merging

2023-11-07 12:31 UTC, JkSelf commented
@oerling @Yuhta @mbasmanova We included this pull request into Gluten and encountered the following exception caused by [this code](https://github.com/facebookincubator/velox/blob/a237661d43d4cb8519f25e9dfab71e56e0d431f7/velox/common/memory/HashStringAllocator.cpp#L549), where header->end() is an empty string (""). Do you have any suggestions or insights? Thank you.

```
C  [libvelox.so+0x12ab99b4]  facebook::velox::HashStringAllocator::storeStringFast(char const*, int, char*)+0x1a8
C  [libvelox.so+0x12ab7384]  facebook::velox::HashStringAllocator::copyMultipartNoInline(char*, int)+0xaa
C  [libvelox.so+0x10c481da]  facebook::velox::HashStringAllocator::copyMultipart(char*, int)+0x4e
C  [libvelox.so+0x10c5097e]  void facebook::velox::exec::RowContainer::storeWithNulls<(facebook::velox::TypeKind)7>(facebook::velox::DecodedVector const&, int, char*, int, int, unsigned char)+0x128
C  [libvelox.so+0x10c427c4]  _ZZZN8facebook5velox4exec12RowContainer5storeERKNS0_13DecodedVectorEiPciENKUlvE0_clEvENKUlvE_clEv+0x596
C  [libvelox.so+0x10c42d80]  _ZZN8facebook5velox4exec12RowContainer5storeERKNS0_13DecodedVectorEiPciENKUlvE0_clEv+0x1c6
C  [libvelox.so+0x10c42efd]  facebook::velox::exec::RowContainer::store(facebook::velox::DecodedVector const&, int, char*, int)+0x15d
C  [libvelox.so+0x10e3932e]  facebook::velox::exec::TopN::addInput(std::shared_ptr<facebook::velox::RowVector>)+0x228
C  [libvelox.so+0x10c055dd]  facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>&, std::shared_ptr<facebook::velox::RowVector>&)+0xf19
C  [libvelox.so+0x10c0379d]  facebook::velox::exec::Driver::next(std::shared_ptr<facebook::velox::exec::BlockingState>&)+0xbf
C  [libvelox.so+0x10cba9f7]  facebook::velox::exec::Task::next(folly::SemiFuture<folly::Unit>*)+0x65b
```

2023-11-07 12:32 UTC, mbasmanova commented
I'm also seeing this error:

```
VeloxRuntimeError: size <= kSizeMask
   at Unknown.# 0  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)(Unknown Source)
   at Unknown.# 1  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, facebook::velox::detail::CompileTimeEmptyString>(facebook::velox::detail::VeloxCheckFailArgs const&, facebook::velox::detail::CompileTimeEmptyString)(Unknown Source)
   at Unknown.# 2  facebook::velox::HashStringAllocator::storeStringFast(char const*, int, char*)(Unknown Source)
   at Unknown.# 3  facebook::velox::HashStringAllocator::copyMultipartNoInline(char*, int)(Unknown Source)
   at Unknown.# 4  facebook::velox::exec::RowContainer::store(facebook::velox::DecodedVector const&, int, char*, int)(Unknown Source)
   at Unknown.# 5  facebook::velox::exec::HashBuild::addInput(std::shared_ptr<facebook::velox::RowVector>)(Unknown Source)
```

@laithsakka Laith saw a Join Fuzzer failure that's probably similar or same.

@oerling I believe Orri is aware of these and is working on a fix.

2023-11-07 12:36 UTC, JkSelf commented
> I'm also seeing this error:
> 
> ```
> VeloxRuntimeError: size <= kSizeMask
>    at Unknown.# 0  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)(Unknown Source)
>    at Unknown.# 1  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, facebook::velox::detail::CompileTimeEmptyString>(facebook::velox::detail::VeloxCheckFailArgs const&, facebook::velox::detail::CompileTimeEmptyString)(Unknown Source)
>    at Unknown.# 2  facebook::velox::HashStringAllocator::storeStringFast(char const*, int, char*)(Unknown Source)
>    at Unknown.# 3  facebook::velox::HashStringAllocator::copyMultipartNoInline(char*, int)(Unknown Source)
>    at Unknown.# 4  facebook::velox::exec::RowContainer::store(facebook::velox::DecodedVector const&, int, char*, int)(Unknown Source)
>    at Unknown.# 5  facebook::velox::exec::HashBuild::addInput(std::shared_ptr<facebook::velox::RowVector>)(Unknown Source)
> ```
> 
> @laithsakka Laith saw a Join Fuzzer failure that's probably similar or same.
> 
> @oerling I believe Orri is aware of these and is working on a fix.

@mbasmanova Got it. Thanks for your prompt reply.