Make ByteStream::size() consistent across use cases
facebookincubator/velox pull request #7520
Opened 2023-11-10 21:37 UTC by oerling

ByteStream::size is expected to have the semantics of the length of std::stringstream. It is the offset of the first unwritten byte from the start. This does not move backward when seeking to mid stream and writing, for example.  been written.

Adds a test to verify proper function when randomly overwriting a ByteStream backed by HashStringAllocator multipart entries.

2023-11-28 19:12 UTC, xiaoxmeng commented on velox/common/memory/StreamArena.h
> +  /// 'lastRange' is non-nullptr, it is the last range of the stream
Can you describe a bit why we need lastRange?

2023-11-29 17:21 UTC, mbasmanova requested changes
@oerling Can we then remove a TODO from RowContainer.cpp?

```
  // TODO Fix ByteStream::size() API. @oerling is looking into that.
  // Fix the 'size' of the std::string_view.
  // stream.size() is the capacity
  // stream.size() - stream.remainingSize() is the size of the data + size of
  // 'next' links (8 bytes per link).
  auto readStream = prepareRead(row, offset);
  const auto size = readStream.size();
  valueAt<std::string_view>(row, offset) =
      std::string_view(reinterpret_cast<char*>(position.position), size);
```

2023-11-29 17:24 UTC, mbasmanova commented on velox/common/memory/ByteStream.h
> +  explicit ByteInputStream(const ByteStream& stream);
Why do we need this? Looks like we are brining back confusion and mixing of input and output streams.

2023-11-29 20:43 UTC, mbasmanova commented on velox/exec/RowContainer.h
> +      return compareStringEqual(
Looks like this is the problematic change that breaks aggregations and was just reverted. Let's make sure it doesn't sneak back in accidentally. CC: @xiaoxmeng

2023-12-01 07:47 UTC, xiaoxmeng reviewed
@oerling thanks for the update % minors.

2023-12-01 07:47 UTC, xiaoxmeng commented on velox/common/memory/StreamArena.h
> +  /// adding the first range to a stream. The memory is stays owned by
```
s/is stays/stays/
```

2023-12-04 18:00 UTC, xiaoxmeng approved these changes
@oerling thanks for the update!

2023-12-05 18:39 UTC, closed without merging