Add Exchange Fuzzer
facebookincubator/velox pull request #7848
Opened 2023-12-03 22:07 UTC by oerling

Add Exchange Fuzzer

Fuzzes types and vectors and shuffles these through an exchange with
random width and random buffer sizes. Nullness and data size limits
are also fuzzed. Validates results by comparing checksums between a
shuffle plan and a local only plan.

Adds a timeout to LocalExchangeSource. Exchange without timeout will
hang if run for long enough. If all exchange sources are not being
read at all times, the window of sources being read must move if no
data is coming. C1 reads P2 and C2 reads P1. P1 cannot advance because
C1 has not read its stuff. P2 cannot advance because C2 has not read
its stuff. P1 and P2 have outgoing uffers full. the situation can only
clear if the consumers move to the next producer if data is not
coming.

Adds a limit to VectorFuzzer for repeated data inside constant. This
is liable to OOM when flattening the repeated data.

2023-12-04 19:43 UTC, mbasmanova commented
Did this new Fuzzer catch any bugs?

2023-12-04 23:36 UTC, bikramSingh91 commented on velox/exec/tests/ExchangeFuzzer.cpp
> +      int32_t targetWidth = randInt(1, 200);
bit: how about numTargetTasks or numDestinationTasks?

2023-12-04 23:47 UTC, bikramSingh91 commented
Thanks @oerling for adding this.

Just thinking out aloud for future enhancements:
- different key types
- composite partitioning keys
- using 'replicateNullsAndAny_'
- using round-robin

2023-12-07 18:45 UTC, oerling commented
Can be added later. For now this is too test serde \optimizations and these are covered as is.

 

 

 

From: Bikramjeet Singh Vig ***@***.***> 
Sent: Monday, December 4, 2023 3:48 PM
To: facebookincubator/velox ***@***.***>
Cc: oerling ***@***.***>; Mention ***@***.***>
Subject: Re: [facebookincubator/velox] Add Exchange Fuzzer (PR #7848)

 

Thanks @oerling <https://github.com/oerling>  for adding this.

Just thinking out aloud for future enhancements:

*	different key types
*	composite partitioning keys
*	using 'replicateNullsAndAny_'
*	using round-robin

—
Reply to this email directly, view it on GitHub <https://github.com/facebookincubator/velox/pull/7848#issuecomment-1839748970> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AKPPPT7NERFYVMQVPTPLRY3YHZOLPAVCNFSM6AAAAABAFCQJKKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZZG42DQOJXGA> .
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-12-07 18:51 UTC, mbasmanova commented on velox/exec/tests/utils/LocalExchangeSource.cpp
> +    auto hasBeenCalled = std::make_shared<bool>(false);
Is this a bug fix? If so, would you put it in a separate PR and provide a description of what was wrong and how you are fixing it?

2023-12-08 01:22 UTC, bikramSingh91 approved these changes

2023-12-08 17:40 UTC, pedroerp commented on velox/exec/tests/ExchangeFuzzer.cpp
> +      std::vector<RowVectorPtr>& vectors,
const

2023-12-08 17:40 UTC, pedroerp commented on velox/exec/tests/ExchangeFuzzer.cpp
> +    LOG(INFO) << "Iteration " << iteration << " shuffl " << numSourceTasks
typo "shuffle"

2023-12-08 17:41 UTC, pedroerp commented on velox/exec/tests/ExchangeFuzzer.cpp
> +    for (auto i = 1; i < rowType.size(); ++i) {
not obvious why ignore the first column (because it's the partitioning key?). Could use a comment.

2023-12-08 17:44 UTC, pedroerp commented on velox/exec/tests/ExchangeFuzzer.cpp
> +    std::vector<std::shared_ptr<Task>> tasks;
this method is quite long. Can we move the task creation and set up to a separate helper function?

2023-12-08 17:46 UTC, pedroerp commented on velox/exec/tests/ExchangeFuzzer.cpp
> +      int32_t numSourceTasks,
can these be class members so we don't need to juggle them around?

2023-12-08 17:48 UTC, pedroerp commented on velox/exec/tests/ExchangeFuzzer.cpp
> +      if (FLAGS_inject_failure) {
not sure if I follow this one. Is this flag just so we end up failing and saving the state? Could we just have a "--save_output" flag instead?

2023-12-08 17:50 UTC, pedroerp commented on velox/exec/tests/ExchangeFuzzer.cpp
> +      auto rowType = ROW(std::move(allNames), std::move(allTypes));
nit: move to a `auto rowType = getInputRowType(fuzzer_.randRowType());` method

2023-12-10 17:57 UTC, oerling commented
Some reencoding may take place in shuffle at some future time but now it is always flat. It is absolutely necessary to cap repeat in constants or the thing will oom all the time, e.g.  2% of test cases.

2023-12-11 03:47 UTC, oerling commented
Edited it. I don’t see this being used in any other way than as is, so cutting this in 3 files just makes it longer.

2023-12-12 00:49 UTC, pedroerp commented
@oerling thanks for the edits. Let's move the LocaExchangeSource edits to a separate PR with its own tests (I'm assuming that's a bug fix?)

2023-12-12 02:15 UTC, oerling commented
No extended exchange test can work unless the sources time out. This is explained in he comment. The exchange fuzzer can’t work without, certainly not in the case of wide exchanges and small buffers. 

 

 

From: Pedro Pedreira ***@***.***> 
Sent: Monday, December 11, 2023 4:49 PM
To: facebookincubator/velox ***@***.***>
Cc: oerling ***@***.***>; Mention ***@***.***>
Subject: Re: [facebookincubator/velox] Add Exchange Fuzzer (PR #7848)

 

@oerling <https://github.com/oerling>  thanks for the edits. Let's move the LocaExchangeSource edits to a separate PR with its own tests (I'm assuming that's a bug fix?)

—
Reply to this email directly, view it on GitHub <https://github.com/facebookincubator/velox/pull/7848#issuecomment-1851128462> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AKPPPT6YY4E7MW5MI3JQ3VLYI6SZBAVCNFSM6AAAAABAFCQJKKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJRGEZDQNBWGI> .
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-12-13 21:14 UTC, Yuhta approved these changes

2023-12-14 02:02 UTC, pedroerp requested changes

2023-12-14 02:02 UTC, pedroerp commented on velox/exec/tests/ExchangeClientTest.cpp
> +<<<<<<< HEAD
Looks like there are rebase failures. All CI jobs are failing.

2023-12-14 18:56 UTC, closed without merging