Add key_sampling_percent Scalar function
facebookincubator/velox pull request #8481
Opened 2024-01-23 05:52 UTC by pdabre12

Resol

2024-01-26 20:32 UTC, pdabre12 commented
@majetideepak @aditi-pandit Please review.

2024-02-01 03:13 UTC, aditi-pandit commented
@pdabre12 : Please can you run ExpressionFuzzer for this function and paste results here. https://facebookincubator.github.io/velox/develop/testing/fuzzer.html#how-to-run

2024-02-01 06:23 UTC, pdabre12 commented
Fuzzer output:

```
I20240131 22:21:44.925518 20087581 FuzzerToolkit.cpp:137] Two vectors match.
I20240131 22:21:44.925530 20087581 ExpressionFuzzerVerifier.cpp:363] ==============================> Done with iteration 18586
I20240131 22:21:44.925557 20087581 ExpressionFuzzerVerifier.cpp:160] ==============================> Top 1 by number of rows processed
I20240131 22:21:44.925563 20087581 ExpressionFuzzerVerifier.cpp:162] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240131 22:21:44.925570 20087581 ExpressionFuzzerVerifier.cpp:166] key_sampling_percent 18587 100.00% 300770
I20240131 22:21:44.925580 20087581 ExpressionFuzzerVerifier.cpp:172] ==============================> Bottom 1 by number of rows processed
I20240131 22:21:44.925585 20087581 ExpressionFuzzerVerifier.cpp:174] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240131 22:21:44.925590 20087581 ExpressionFuzzerVerifier.cpp:179] key_sampling_percent 18587 100.00% 300770
I20240131 22:21:44.925597 20087581 ExpressionFuzzerVerifier.cpp:192] ==============================> All stats sorted by number of times the function was chosen
I20240131 22:21:44.925602 20087581 ExpressionFuzzerVerifier.cpp:194] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240131 22:21:44.925607 20087581 ExpressionFuzzerVerifier.cpp:198] key_sampling_percent 18587 100.00% 300770
E20240131 22:21:44.925613 20087581 ExpressionFuzzerVerifier.cpp:369] Total iterations: 18587
E20240131 22:21:44.925618 20087581 ExpressionFuzzerVerifier.cpp:370] Total failed: 0
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```

2024-02-01 19:17 UTC, pdabre12 commented on velox/functions/prestosql/StringFunctions.h
> +        sizeof(result) == kTypeLength,
Removed this check.

2024-02-01 19:17 UTC, pdabre12 commented
@aditi-pandit  Thanks for the review.
Addressed the comments, PTAL.

2024-02-02 19:34 UTC, aditi-pandit approved these changes
Thanks @pdabre12

2024-02-02 19:34 UTC, aditi-pandit commented
@Yuhta, @kagamiori : Please could either of you take a look. Thanks.

2024-02-05 00:55 UTC, aditi-pandit commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
@majetideepak : My understanding is that he wanted a bit by bit copy from the int64 hash to the double value returned.

2024-02-05 01:16 UTC, majetideepak requested changes
Double precision values have a specific bit layout. We need to ensure the correctness of memcpy vs cast from int64_t to double here.

2024-02-05 01:16 UTC, majetideepak commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
Double precision has a specific layout in C++. Bit by bit copy from int64_t could result in a NaN double.
The right approach is to use the int64 to double cast.
Are the results expected to match on the Java side?

2024-02-05 01:33 UTC, majetideepak commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
Why can't we use `folly::Endian::big(hash)` below?
I feel the memcpy is redundant.

2024-02-05 11:42 UTC, majetideepak commented
@aditi-pandit, good catch on the SQL function. I verified that `key_sampling_function` works on Prestissimo. We should not need another function.

2024-02-05 21:01 UTC, pdabre12 commented
`key_sampling_percent` function does not seem to work without adding the extra `key_sampling_percent` function on the velox side.

Without function added: 
```
presto:tpch> select key_sampling_percent(comment) from orders limit 5;
Query 20240205_033404_00017_tfhbi failed:  Scalar function name not registered: presto.default.key_sampling_percent, called with arguments: (VARCHAR).
```

With function added:

```
presto:tpch> select key_sampling_percent(comment) from orders limit 5;
          _col0          
-------------------------
  6.182252096053023E-138 
   9.325169862508376E291 
 3.6936313139242443E-292 
   -8.57933126404383E257 
 3.3387410329289704E-174 
(5 rows)
```


Also adding the `key_sampling_percent` function on the Velox side, fixes https://github.com/prestodb/presto/issues/20514

2024-02-05 23:55 UTC, majetideepak commented
I tested with a constant earlier. This plan was likely optimized. But with a table column, I get the following error
```
select key_sampling_percent(o_comment) from tpch.sf1.orders limit 5;

Query 20240205_233919_00004_rcbzm, FAILED, 1 node
Splits: 5 total, 0 done (0.00%)
[Latency: client-side: 389ms, server-side: 294ms] [0 rows, 0B] [0 rows/s, 0B/s]

Query 20240205_233919_00004_rcbzm failed:  Scalar function name not registered: presto.default.from_ieee754_64, called with arguments: (VARBINARY).
```
There seems to be another problem with the registration of `from_ieee754_64`. I see that we do not have E2E tests as well.

@pdabre12 can you share your Presto core config? 
Having another person verify the output will help resolve this. @aditi-pandit, @czentgr, can on of you please share the output from using the `key_sampling_percent` function in Prestissimo today?

2024-02-06 04:55 UTC, czentgr commented
I get the same as Pratik with a slightly different query:
```
presto:sf1> select key_sampling_percent(c) from (values ('foobar')) t(c);
Query 20240205_040232_00008_nhcb8 failed:  Scalar function name not registered: presto.default.key_sampling_percent, called with arguments: (VARCHAR).
```

The coordinator has:
```
VeloxUserError:  Scalar function name not registered: presto.default.key_sampling_percent, called with arguments: (VARCHAR).
```
So it goes to Prestissimo.

The plan shows the key_sampling_percent:
```
presto:sf1> explain (type distributed) select key_sampling_percent(c) from (values ('foobar')) t(c);
                                                       Query Plan
------------------------------------------------------------------------------------------------------------------------
 Fragment 0 [SINGLE]
     Output layout: [key_sampling_percent]
     Output partitioning: SINGLE []
     Stage Execution Strategy: UNGROUPED_EXECUTION
     - Output[PlanNodeId 8][_col0] => [key_sampling_percent:double]
             Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 64.00, memory: 0.00, network: 0.00}
             _col0 := key_sampling_percent (1:35)
         - Project[PlanNodeId 4][projectLocality = LOCAL] => [key_sampling_percent:double]
                 Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 64.00, memory: 0.00, network: 0.00}
                 key_sampling_percent := key_sampling_percent(CAST(field AS varchar)) (1:66)
             - LocalExchange[PlanNodeId 178][ROUND_ROBIN] () => [field:varchar(6)]
                     Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 55.00, memory: 0.00, network: 0.00}
                 - Values[PlanNodeId 0] => [field:varchar(6)]
                         Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 0.00, memory: 0.00, network: 0.00}
                         (VARCHAR'foobar')


(1 row)
```

I have some problems with the TPCH connector - while I can run queries it tells me no node available for TPCH.
```
presto:sf1> select key_sampling_percent(comment) from orders limit 5;
Query 20240205_040543_00012_nhcb8 failed: No nodes available to run query
```
Some local setup issue I suppose.

2024-02-06 17:19 UTC, majetideepak commented
If you set `inline-sql-functions=false`, we will see `Scalar function name not registered: presto.default.key_sampling_percent`

2024-02-06 17:29 UTC, aditi-pandit commented
I see comment for this flag in getNativeWorkerSystemProperties
"// By default, Presto will expand some functions into its SQL equivalent (e.g. array_duplicates()).
 // With Velox, we do not want Presto to replace the function with its SQL equivalent.
// To achieve that, we set inline-sql-functions to false."

Will need to investigate into it.

2024-02-06 17:31 UTC, czentgr commented
Yes, was about to make the same comment as Aditi.

When I execute the query it works for me with Prestissimo now.
```
presto:sf1> set session inline_sql_functions=true;
SET SESSION
presto:sf1> select key_sampling_percent(c) from (values ('foobar')) t(c);
          _col0
-------------------------
 1.0670186722451606E-143
(1 row)
presto:sf1> explain (type distributed) select key_sampling_percent(c) from (values ('foobar')) t(c);
                                                                            Query Plan                  >
-------------------------------------------------------------------------------------------------------->
 Fragment 0 [SINGLE]                                                                                    >
     Output layout: [key_sampling_percent]                                                              >
     Output partitioning: SINGLE []                                                                     >
     Stage Execution Strategy: UNGROUPED_EXECUTION                                                      >
     - Output[PlanNodeId 8][_col0] => [key_sampling_percent:double]                                     >
             Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 64.00, memory: 0.00, network: 0>
             _col0 := key_sampling_percent (1:35)                                                       >
         - Project[PlanNodeId 4][projectLocality = LOCAL] => [key_sampling_percent:double]              >
                 Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 64.00, memory: 0.00, networ>
                 key_sampling_percent := ((abs(from_ieee754_64(xxhash64(CAST(CAST(field AS varchar) AS v>
             - LocalExchange[PlanNodeId 180][ROUND_ROBIN] () => [field:varchar(6)]                      >
                     Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 55.00, memory: 0.00, ne>
                 - Values[PlanNodeId 0] => [field:varchar(6)]                                           >
                         Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 0.00, memory: 0.00,>
                         (VARCHAR'foobar')                                                              >
                                                                                                        >
                                                                                                        >
(1 row)
```

2024-02-06 20:23 UTC, pdabre12 commented
The query works for me too on the Prestissimo side, with  `inline_sql_functions=true`.
However, still getting the `Scalar function name not registered: presto.default.key_sampling_percent` while trying to run the query in https://github.com/prestodb/presto/issues/20514. 

```
presto:tpch> set session inline_sql_functions=true;
SET SESSION
presto:tpch> set session KEY_BASED_SAMPLING_ENABLED=true;
SET SESSION
presto:tpch> select count(1) from orders join lineitem using(orderkey);

Query 20240206_202015_00021_rxg96, FAILED, 1 node, 11 splits

WARNING: Sampled the following columns/derived columns at 10.0 percent:
	orderkey from HiveTableHandle{schemaName=tpch, tableName=orders, analyzePartitionValues=Optional.empty}
	orderkey_0 from HiveTableHandle{schemaName=tpch, tableName=lineitem, analyzePartitionValues=Optional.empty}


Query 20240206_202015_00021_rxg96, FAILED, 1 node
Splits: 11 total, 0 done (0.00%)
[Latency: client-side: 0:01, server-side: 0:01] [0 rows, 0B] [0 rows/s, 0B/s]

Query 20240206_202015_00021_rxg96 failed:  Scalar function name not registered: presto.default.key_sampling_percent, called with arguments: (VARCHAR).
```

Query Plan:

```
- Output[PlanNodeId 13][_col0] => [count:bigint]                                                                                                                                                                                                >
         _col0 := count (1:16)                                                                                                                                                                                                                   >
     - Aggregate(FINAL)[PlanNodeId 8] => [count:bigint]                                                                                                                                                                                          >
             count := "presto.default.count"((count_12)) (1:16)                                                                                                                                                                                  >
         - LocalExchange[PlanNodeId 500][SINGLE] () => [count_12:bigint]                                                                                                                                                                         >
             - RemoteStreamingExchange[PlanNodeId 506][GATHER] => [count_12:bigint]                                                                                                                                                              >
                 - Aggregate(PARTIAL)[PlanNodeId 504] => [count_12:bigint]                                                                                                                                                                       >
                         count_12 := "presto.default.count"(*) (1:16)                                                                                                                                                                            >
                     - InnerJoin[PlanNodeId 418][("orderkey_0" = "orderkey")] => []                                                                                                                                                              >
                             Estimates: {source: CostBasedSourceInfo, rows: 47,377 (416.40kB), cpu: 1,948,252.50, memory: 121,500.00, network: 608,917.50}                                                                                       >
                             Distribution: PARTITIONED                                                                                                                                                                                           >
                         - RemoteStreamingExchange[PlanNodeId 445][REPARTITION] => [orderkey_0:bigint]                                                                                                                                           >
                                 Estimates: {source: CostBasedSourceInfo, rows: 54,158 (475.99kB), cpu: 974,835.00, memory: 0.00, network: 487,417.50}                                                                                           >
                             - TableScan[PlanNodeId 1][TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=lineitem, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.lineitem{filter=(key>
                                     Estimates: {source: CostBasedSourceInfo, rows: 54,158 (475.99kB), cpu: 487,417.50, memory: 0.00, network: 0.00}                                                                                             >
                                     LAYOUT: tpch.lineitem{filter=(key_sampling_percent(CAST(orderkey AS varchar))) <= (DOUBLE'0.1')}                                                                                                            >
                                     orderkey_0 := orderkey:bigint:0:REGULAR (1:42)                                                                                                                                                              >
                         - LocalExchange[PlanNodeId 483][HASH] (orderkey) => [orderkey:bigint]                                                                                                                                                   >
                                 Estimates: {source: CostBasedSourceInfo, rows: 13,500 (118.65kB), cpu: 364,500.00, memory: 0.00, network: 121,500.00}                                                                                           >
                             - RemoteStreamingExchange[PlanNodeId 446][REPARTITION] => [orderkey:bigint]                                                                                                                                         >
                                     Estimates: {source: CostBasedSourceInfo, rows: 13,500 (118.65kB), cpu: 243,000.00, memory: 0.00, network: 121,500.00}                                                                                       >
                                 - TableScan[PlanNodeId 0][TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=orders, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.orders{filter=(key>
                                         Estimates: {source: CostBasedSourceInfo, rows: 13,500 (118.65kB), cpu: 121,500.00, memory: 0.00, network: 0.00}                                                                                         >
                                         LAYOUT: tpch.orders{filter=(key_sampling_percent(CAST(orderkey AS varchar))) <= (DOUBLE'0.1')}                                                                                                          >
                                         orderkey := orderkey:bigint:0:REGULAR (1:30)
```

2024-02-15 05:41 UTC, majetideepak commented
> select count(1) from orders join lineitem using(orderkey);

@pdabre12 can you try setting `inline_sql_functions=true` in the config.properties instead of the session?

I think we need to land this function irrespective since its a small one and we will not have inconsistencies with and without `inline_sql_functions`

2024-02-15 07:04 UTC, majetideepak commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
@pdabre12 can you verify that ` memcpy(&result, &hash, kTypeLength);` is redundant?

2024-02-15 08:09 UTC, majetideepak commented
The point is that Presto Java can execute this function with both `inline-sql-functions=true` and `inline-sql-functions=false`

2024-02-16 01:57 UTC, pdabre12 commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
@majetideepak Without the  `memcpy(&result, &hash, kTypeLength);` I am getting results which do not match the Java side.

2024-02-16 02:40 UTC, pdabre12 commented
> > select count(1) from orders join lineitem using(orderkey);
> 
> @pdabre12 can you try setting `inline-sql-functions=true` in the config.properties instead of the session?
> 
> I think we need to land this function irrespective since its a small one and we will not have inconsistencies with and without `inline_sql_functions`

I tried setting `inline-sql-functions=true` in the config.properties , still facing the same error.

2024-02-16 05:56 UTC, majetideepak commented
> I tried setting `inline-sql-functions=true` in the config.properties , still facing the same error.

Thanks for verifying!

2024-02-16 06:26 UTC, majetideepak commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
We need `memcpy` (double value) for the `abs` function. But we do switch the bytes twice. The following should work
```
    int64_t hash = XXH64(string.data(), string.size(), 0);
    memcpy(&result, &hash, kTypeLength);
    result = fmod(abs(result), 100) / 100;
```

2024-02-16 06:50 UTC, pdabre12 commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
Thank you for this, this does work. 
Yes , I was switching the bytes twice, was not really needed.

> Double precision has a specific layout in C++. Bit by bit copy from int64_t could result in a NaN double. The right approach is to use the int64 to double cast. Are the results expected to match with the Java side?

However, one quick question, as we are still using memcpy for a bit by bit copy, we can technically still get a Nan double with this approach as well?

2024-02-16 07:30 UTC, majetideepak commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
I looked into this and figured out that NaN is a possible and allowed output. The Java implementation uses `Double.longBitsToDouble` that can return NaN as well.
I see that `memcpy` is the closest C++ solution for Java's `longBitsToDouble` implementation.
I do see some nuances around NaN https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#longBitsToDouble-long- that are probably Java specific.

2024-02-16 21:29 UTC, pdabre12 commented on velox/functions/prestosql/StringFunctions.h
> +    memcpy(&result, &hash, kTypeLength);
Thank you for the detailed explanation. 
In that case, should we move ahead with this PR?

2024-02-29 17:23 UTC, majetideepak approved these changes

2024-02-29 17:23 UTC, majetideepak commented
@pdabre12 can you rebase with the latest main? The branch is 2 weeks old. Thanks!

2024-02-29 20:40 UTC, pdabre12 commented
@majetideepak Thanks for the review, rebased with the latest main.

2024-03-01 01:41 UTC, majetideepak commented
@pdabre12 I asked a question in the Presto Slack about this to confirm we did not miss anything
https://prestodb.slack.com/archives/CLYMEEJ6S/p1709257204162099

2024-03-01 02:27 UTC, pdabre12 commented
> @pdabre12 I asked a question in the Presto Slack about this to confirm we did not miss anything https://prestodb.slack.com/archives/CLYMEEJ6S/p1709257204162099

Thank you.

2024-03-07 19:43 UTC, pdabre12 commented
Closing this as it's no longer needed.

2024-03-07 19:43 UTC, closed without merging

2024-07-17 19:05 UTC, kgpai commented
@pdabre12 @majetideepak I am curious why this was closed - would be great if you can add that reasoning here.

2024-07-17 19:18 UTC, pdabre12 commented
@kgpai Since `key_sampling_percent` is a SQL function it should not need an implementation in the worker eval (in this case Prestissimo) when `inline_sql_functions=true`, as a result adding the `key_sampling_percent` scalar function was not needed.
However, running `key_sampling_percent` in Prestissimo exposed a bug which is described here : https://github.com/prestodb/presto/issues/22085.

2024-07-17 19:32 UTC, kgpai commented
@pdabre12  Thanks !

2024-07-17 20:11 UTC, amitkdutta commented
@pdabre12 The worker implementation is required to make the query performant. If the function is missing and inline is set to true in a C++ cluster, the fallback to coordinator implementation makes the query significantly slow. We should add the implemenation natively so that worker can run it instead of relying on coordinator fallback.

2024-07-18 21:54 UTC, majetideepak commented
@amitkdutta Is it the case that the inline function executes on the coordinator? I am not an expert here but I thought the coordinator would expand this function to `(abs(from_ieee754_64(xxhash64(cast(input as varbinary)))) % 100) / 100.` which then executes on the C++ worker. If this is not the case, then we should add this function in C++.
https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/sql/SimpleSamplingPercent.java

2024-07-18 23:18 UTC, aditi-pandit commented
@amitkdutta : Even if we have a native execution it would mean we inline the same logic into a single scalar function. 

So evaluating (abs(from_ieee754_64(xxhash64(cast(input as varbinary)))) % 100) / 100 vs key_sampling_percent(input) in the Expression framework. Understand that evaluating the tree is slower than just the single function. But are you suggesting it is so much slower ? Do you have a microbenchmark showing the difference ?