Fix broken link to design philosophy document
facebookincubator/velox pull request #9461
Opened 2024-04-12 00:15 UTC by shrinaththube

<img width="1721" alt="image" src="https://github.com/facebookincubator/velox/assets/12885505/07997adc-64f2-4f72-b294-0872cce0c56e">

The `Velox Design Philosophy, Principles, and Values` document link has an extra `/docs/community/` in the link. It is giving 404 when clicked. I have updated the link to `./design-philosophy.md.`

It is a minor document fix, so I did not open an issue. Please let me know if you need one. Thank you!

2024-04-12 00:16 UTC, mbasmanova approved these changes
Thanks.

2024-04-12 01:20 UTC, pedroerp commented
This is not a real markdown file. It is supposed to be accessed through the website: https://velox-lib.io/docs

Changing the link here will break the website link

2024-04-12 01:21 UTC, pedroerp requested changes
Check comment above.

2024-04-12 18:05 UTC, shrinaththube commented
Thank you, @pedroerp, for the insight! 

The link on the website is broken, too. I tried different combinations on the local dev playground, but it didn't work. On the website, I am getting extra `/docs/` in the URL, which is causing 404 when clicked. Surprisingly, it is working correctly for the `next` section link and in the sidebar. I am posting some screenshots here for the reference. Meanwhile I am checking with [Docusaurus](https://docusaurus.io/) discord channel. I am hoping someone will give me the correct way to add the link :) 

<img width="1724" alt="image" src="https://github.com/facebookincubator/velox/assets/12885505/5b412c15-c813-43e4-a71d-251b0a6951a7">


<img width="1722" alt="image" src="https://github.com/facebookincubator/velox/assets/12885505/f3e93d23-b6b2-4287-824c-6df2a8aec02c">

<img width="1722" alt="image" src="https://github.com/facebookincubator/velox/assets/12885505/218b8e95-c93f-4b7c-8d2e-b30b15a11c1a">

2024-09-09 16:03 UTC, pedroerp commented
I remember fixing this at some point. I'll close it for now, but please re-open if that is not the case.

2024-09-09 16:03 UTC, closed without merging